### ISSUE TITLE
Help to run your config on QNAP NAS

### ISSUE THREAD

**Issue by salexes** [animosity22/homescripts#10]
Hello animosity22,

I read a lot about this config collection and from what I see you seem to have found the optimal setup which is blazingly fast.

I just got my QNAP NAS and just started with my journey and was hoping for your help to setup everything as perfect as possible.

I want to use Rclone with google drive for my Plex Library.

I have installed the Plex QPKG File from the plex website and also installed RClone QPKG from here: https://www.qnapclub.eu/en/qpkg/330

How do I need to proceed now? Could you help me out with that?

cheers,
salexes

**Comment by animosity22** [comment]
I'd probably write a post on the Rclone forums as I have no idea on a QNAP NAS as I've never used one. I can only help out on the Linux side as that's my knowledge.
