### ISSUE TITLE
dropbox experience with 128 character path limit (standard filename encryption)

### ISSUE THREAD

**Issue by ak2k** [animosity22/homescripts#100]
Hi @animosity22,
Thank you for posting your config and being so responsive to folks' questions!
I noticed that your rclone.conf uses 'standard' filename encryption with Dropbox. 
Have you found yourself bumping up against the effective 128 character path limit in your use? That is, do you find that you need to take any particular actions to prevent your various automated tools from generating errors while trying to place files on this volume?

What's prompting my question is that I am noticing that my migration from Drive is emitting errors 'Failed to copy: file name too long' and I noticed [this thread](https://forum.rclone.org/t/rclone-vfs-cache-says-file-name-too-long/31535/2) which suggests that 'base32768' encoding would permit longer names. I noticed that you're not using this, so wondered if you were taking any upstream steps to prevent errors.

Thank you for any thoughts/reactions you have!

**Comment by animosity22** [comment]
I've never had a problem with any path length that I've noticed anyway.

I'd have to reupload my library for a non issue so I never thought about making a change.

![image](https://user-images.githubusercontent.com/5088712/195667749-5abb89fa-ba3f-4484-8d2d-a08a5ebd38ec.png)

I'd imagine for a new library / setup, I'd probably say that's a great idea to ensure you don't have that problem.

I generally have my mounts different for Movies/TV and only recently I started adding Season folders for TV. Movies would never hit that.

I've yet to notice it for any TV shows.

I do automated log monitoring for errors and such so if it did creep up, I feel pretty confident I'd notice it.

**Comment by animosity22** [comment]
I actually wasn't planning to change a thing as the base encoding is experimental and not fully tested and I have no problems with my current setup.

No reason for me to change currently.

**Comment by animosity22** [comment]
Not really as when I migrated, all the data can be grabbed again if I had any issues so I was just bulk moving without much care.

I was toying around with new naming formats for Sonarr/Radarr and did hit some path name issues so I'm going to play around with it a bit more.

**Comment by animosity22** [comment]
I'll close this out as I don't see the need for me to change in my setup as some folks seem to report issues and I've been fine with the setup I use currently.

Thanks for the feedback.
