### ISSUE TITLE
Replace rc-addr with url when connecting to a specific rc server

### ISSUE THREAD

**Issue by darthShadow** [animosity22/homescripts#103]
Refer: https://github.com/rclone/rclone/issues/6641

`rc-addr` was updated to support multiple listening addresses and no longer works for connecting to a specific rc server. As per the docs, `url` is the actual parameter to be used for that purpose and it works fine.

**Comment by animosity22** [comment]
Thanks!

I changed the rc-addr in the post actions to use url and they seem to work again:

https://github.com/animosity22/homescripts/commit/94828d51f6b1a1055ea22824e2ef559833a2be44
