### ISSUE TITLE
plex-library-stats Credit Markers

### ISSUE THREAD

**Issue by g4m3r7ag** [animosity22/homescripts#104]
Any chance of updating the plex-library-stats script to also check for the number of items with/without credit markers in all the libraries?

**Comment by animosity22** [comment]
Maybe?

I toyed around and I think I got the right query. 

I need to validate once I scan stuff for credits it actually does what I think.

**Comment by animosity22** [comment]
Pretty sure it's working ok as I've been testing a bit as TV shows and Movies are viable for this so I had to tweak it a bit.

Takes some time as you have to analyze everything again for the end credits.
