### ISSUE TITLE
"removed burst to avoid tps issues based on how burst works"

### ISSUE THREAD

**Issue by WoisWoi** [animosity22/homescripts#105]
Hi,

Is it possible to have more information on this : "[removed burst to avoid tps issues based on how burst works](https://github.com/animosity22/homescripts/commit/254b26ae12770c71467f3e1fa237f5e55add362d)" please ?

I'd like to understand if I should (also) do it :)

Thansk you!

**Comment by animosity22** [comment]
I misunderstood how burst works and had it explained a bit.

Dropbox seems like rate limit at 12 TPS.

If you have burst and 12 tps, you save up the 'burst' so you get 24 TPS.

I never want to go past 12 TPS so burst should be 0. I tested this quite a bit with mass moving of things and no rate limiting.
