### ISSUE TITLE
Modtime

### ISSUE THREAD

**Issue by drag0n141** [animosity22/homescripts#108]
Hi,

i have one question. I am running my setup now with dropbox too. But i have found a problem. With dropbox there are no modtimes on the folders. Normally thats not a problem but Plex refresh the metadata of a File when it sees the folder is changed. You have that problem too?

EDIT: I have now created an FR for that https://github.com/rclone/rclone/issues/6986

**Comment by animosity22** [comment]
No, that's not an issue actually so not sure why you'd be seeing that.

Rclone doesn't do modtimes on directories so that's not a feature request that will happen.

If Plex is refreshing metadata, it has something to do with the file, not the directory timestamp as it only cares about the file.

**Comment by drag0n141** [comment]
Thats Not correct, they said it refresh when the Folder hast changed. 

https://forums.plex.tv/t/metadata-refreshing-when-i-select-a-movie/839771

**Comment by animosity22** [comment]
Nah, that post you are asking something different. 

Plex analyzes a file when you play it as that is probably your confusion and it logs that. It has nothing do with the higher level directory timestamp.

**Comment by drag0n141** [comment]
Then it analyze the file nur Problem is the Same. After restart of Rclone and remount Plex did it again. And this can only be because of the modtime of the Folder.

**Comment by animosity22** [comment]
I really don't see an issue so not sure what else I can offer as it's nothing related to my scripts or how they are being used.

If it is the folder time, I guess wait the 1/2 second it takes or get someone to support directory times but that's been around for 5+ years so it's not really important enough for anyone to work on.

Closing out.
