### ISSUE TITLE
Migration...

### ISSUE THREAD

**Issue by shawnp0wers** [animosity22/homescripts#110]
Well, Google finally called my bluff. Or my procrastination, or whatever.

They moved my "unlimited" plan to 5TB, and since I currently have 60TB stored, I have 60 days to move away. (And they notify me today, on my birthday... great gift, ugh)

My question is about what settings you found to be most effective to migrate from Google Drive (via rclone) to Dropbox Enterprise (via rclone). I was tempted to leave my files (movies and tv shows mostly) unencrypted on Dropbox for ease of access, but that makes me uncomfortable, so I'll more than likely be moving from encrypted rclone on Google Drive to encrypted rclone on Dropbox.

Since you did a similar migration, I'm curious if you have any pointers, configuration-wise, for the migration itself.

**Comment by animosity22** [comment]
I did nothing special.

rclone move GD: DB: and did ~9-10TB per day.

**Comment by shawnp0wers** [comment]
Oh sweet, thank you again!

**Comment by mkeguy106** [comment]
Sorry to comment on a closed issue.  Google finally got my drive also.  Are you guys just signing up for DB Advanced?  3 users?

**Comment by b-zig** [comment]
During the migrations was your DB still getting updated to GDrive? Also migrating to dropbox and i'm going to be cutoff from uploading to GDrive before the migration is completed. Leaving me in kinda dead in the water for new content. Is the only solution to keep content local until migration is completed to move plex mounts over?

**Comment by shawnp0wers** [comment]
Hmm... you might be able to do some sort of magic with mergefs while you move from gdrive to dropbox. I'd have to think through the logic, but I'd think that would give you a full view of your entire library, half in read-only mode from gdrive, and half in dropbox. The default share in mergefs could be on the dropbox side, so new content is put there...

@animosity22 might have insights regarding why that's a bad idea, but it seems feasible to me.

Be aware that Dropbox is currently limiting quota increases to 10TB/week now. I should still get my library moved over before I stop using gdrive (I'm just syncing to dropbox, not moving), but it's going to mean I have to pay another month of gdrive, because once I transfer 10TB, my dropbox is full until the following week where they'll increase my quota again. It's annoying, but they say it's due to the mass influx of new users. And, I get it.

**Comment by animosity22** [comment]
Yes, you can use mergerfs to combine the DB and GD remotes into one. It works quite well.

**Comment by shawnp0wers** [comment]
And I remember that used to be part of the "normal" way to handle things. As you move from GD to DB (to use Anonymous' nomenclature) -- the mergerfs share just keeps working fine. I'm not sure if there is a need to have it regularly poll for file location shifts or not.

I don't think mergerfs is part of the current set of scripts, as rclone built-in caching has taken its place -- but perhaps the info on mergerfs is still here somewhere.

(Also, yes, I remembered the name wrong, it's mergerfs, not mergefs)

**Comment by shawnp0wers** [comment]
@b-zig -- I'm on my phone, so can't easily look through the current code -- but if the mergerfs stuff is no longer in the current repo, I'd look at older revisions. @animosity22 did a great job with the mount settings.

Also, FML, I can't spell with my thumbs. "Animosity" not "Anonymous" in my last comment.

This repo is such a great resource on using rclone as a cloud-based NAS on your local machines. I'm still extremely grateful after all these years. :)

**Comment by EldonMcGuinness** [comment]
You can try rclone union, but it did not work out well for me.

**Comment by b-zig** [comment]
Thanks everyone! I'm still using mergerFS in my setup, will combine both GD:DB and set my upload scripts to DB.
