### ISSUE TITLE
rclone --default-time

### ISSUE THREAD

**Issue by ak2k** [animosity22/homescripts#111]
Hi @animosity22, I noticed that you don't seem to be using [the --default-time option](https://github.com/rclone/rclone/issues/6986) in your rclone Dropbox configs. Have you found that the Plex metadata refresh wasn't enough of a problem for you to warrant doing so?

**Comment by animosity22** [comment]
Thanks for asking.

I was waiting till it came out of beta and never went back.

I copied them up now and I ended up going with a default date of just 1-1-2023 and left it at that.

**Comment by calmcacil** [comment]
Is there an actual benefit to this as far as defining a date goes since rclone defines "2000-01-01T00:00:00Z" as a default when you arent using the option?

**Comment by animosity22** [comment]
I decided to remove the flag I'm using to follow my 'less flags' approach and use the default. I'll update the scripts and close this out.

Thanks for the feedback!
