### ISSUE TITLE
rclone disconnect

### ISSUE THREAD

**Issue by Dulanic** [animosity22/homescripts#13]
So I have starting using your scripts, which magically also seems to correect my 25Mbps cap /w v3 api. Not sure why, but it does. Anwyays, I am finding every day or 2 the rclone service disconnects. I then need to top the service, even though it shows as not running, to disconnect the mount and then rerun the service.

I've kind of looked through the services, and don't see where a reconnect is covered. Any idea for a workaround? I am thinking of just putting in a mounted file to a cron job to stop and start the services, but wondering if you have another idea.

Thinking a cron job like so, but don't want to code it all if I am just missing something.

```
logfile="/opt/cloud-media-scripts/logs/status.log"

if pidof -o %PPID -x "rclone-mount.cron"; then
   echo "$(date "+%d.%m.%Y %T") EXIT: rclone-mount.cron already running."
   exit 1
fi

if [[ -f "/local-media/mountcheck.txt" ]]; then
   echo "$(date "+%d.%m.%Y %T") INFO: Check successful,rclone mounted." | tee -a "$logfile"
   exit
else
   echo "$(date "+%d.%m.%Y %T") ERROR: Drive not mounted, remount in progress." | tee -a "$logfile"
   # Unmount before remounting
   fusermount -uz /local-media | tee -a "$logfile"
   blah blah blah more code
```

**Comment by animosity22** [comment]
I think the goal would be to understand why you are getting a disconnect as I've never had that happen.

In my systemd, I have it autostart on failure:

```
Restart=on-failure
```

In the gmedia-rclone.service file.

What's the error message in the log when it stops working?

**Comment by Dulanic** [comment]
I have that and the error doesn't seem to show. I just logged on /w ssh this morning and saw it again. So sometime between the cron job ran to load files and when i tried to restart it in the morning.,

```
2018/12/07 20:40:44 ERROR : torrent/complete/radarr/The Equalizer 2 (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)__akSXIk/The Equalizer 2 (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)/: Dir.Remove not empty
2018/12/07 20:40:46 ERROR : torrent/complete/radarr/The Equalizer 2 (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)__akSXIk/The Equalizer 2 (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)/: Dir.Remove not empty
2018/12/08 11:06:20 mount helper error: fusermount: failed to access mountpoint /GD: Transport endpoint is not connected
2018/12/08 11:06:20 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```
```

-- Reboot --
Dec 03 14:47:25 mediaserver systemd[1]: Starting gmedia...
Dec 03 14:47:25 mediaserver systemd[1]: Started gmedia.
Dec 09 12:51:27 mediaserver systemd[1]: Stopped gmedia.
-- Reboot --
Dec 09 12:52:23 mediaserver systemd[1]: Starting gmedia...
Dec 09 12:52:23 mediaserver systemd[1]: Started gmedia.

```


```
[Unit]
Description=RClone Service
PartOf=gmedia.service
RequiresMountsFor=/data

[Service]
Type=notify
Environment=RCLONE_CONFIG=/opt/torrent/rclone.conf
ExecStart=/usr/bin/rclone mount gcrypt: /GD \
   --allow-other \
   --buffer-size 1G \
   --dir-cache-time 72h \
   --drive-chunk-size 32M \
   --log-level INFO \
   --log-file /home/dulanic/logs/rclone.log \
   --umask 002 \
   --vfs-read-chunk-size 128M \
   --vfs-read-chunk-size-limit off \
   --allow-non-empty
ExecStop=/bin/fusermount -uz /GD
Restart=on-failure
User=dulanic
Group=dulanic

[Install]
WantedBy=gmedia.service


```

**Comment by animosity22** [comment]
You'd probably need to turn the logs up to debug to capture what the disconnect reason is as it seems to only being showing that it is disconnected.

So I'd change the INFO to DEBUG and restart it. If it's happening frequently, hopefully you can catch the log.

**Comment by Dulanic** [comment]
I'll keep an eye, it seems to be happening every day or 2.

**Comment by animosity22** [comment]
You'd have to check a few things as I'm not sure if it fails and still shows up in /proc/mounts.

```
if grep -qs '/mnt/foo ' /proc/mounts; then
    echo "It's mounted."
else
    echo "It's not mounted."
fi
```

You could check that way.

You could also check if a file is there or

```
felix@gemini:~/scripts$ mountpoint -q /GD && echo "mounted" || echo "not mounted"
mounted
```

**Comment by Dulanic** [comment]
I've got an old script where I used to use a different mount method that worked fine. Worst case, I can edit it to fit your method. It worked no issue, of course I didn't use to see situations where it had to remount either, so I'll keep digging in /w the DEBUG to try to identify why. This method just used a "testing" file and not the full mount check since if the mount failed, the file wouldn't be there.

```
logfile="/opt/cloud-media-scripts/logs/status.log"

if pidof -o %PPID -x "rclone-mount.cron"; then
   echo "$(date "+%d.%m.%Y %T") EXIT: rclone-mount.cron already running."
   exit 1
fi

if [[ -f "/local-media/mountcheck.txt" ]]; then
   echo "$(date "+%d.%m.%Y %T") INFO: Check successful,rclone mounted." | tee -a "$logfile"
   exit
else
   echo "$(date "+%d.%m.%Y %T") ERROR: Drive not mounted, remount in progress." | tee -a "$logfile"
   # Unmount before remounting
   fusermount -uz /local-media | tee -a "$logfile"
   /opt/torrent/rclone mount gd-crypt: /local-media --config /home/dulanic/.config/rclone/rclone.conf \
        --gid=1000 --uid=1000 --tpslimit=4 --cache-workers=5 \
        --cache-chunk-path=/rclone/chunks --buffer-size=0M --cache-db-path=/rclone/cache \
        --cache-tmp-upload-path=/chunks/rclone/uploads \
        --allow-other --allow-non-empty --cache-total-chunk-size=250G --cache-chunk-size=10M \
        --dir-cache-time=160h --cache-info-age=168h \
        --log-file=/opt/cloud-media-scripts/logs/rclone.log --log-level=INFO &
   sleep 5s
   if [[ -f "/local-media/mountcheck.txt" ]]; then
      echo "$(date "+%d.%m.%Y %T") INFO: Remount successful." | tee -a "$logfile"
   else
      echo "$(date "+%d.%m.%Y %T") CRITICAL: Remount failed." | tee -a "$logfile"
   fi
fi
exit
#--cache-tmp-wait-time=24h \

```

**Comment by animosity22** [comment]
Are you torrenting from the mount as well to? I only use the mount for plex so I'm pretty limited in terms of reading only and never writing/doing much else.

**Comment by Dulanic** [comment]
So have no had any disconnects recently, once I split my torrent and media to 2 seperate mounts. So I don't know if it's a "issue" per say that caused it, but I likely willl script a cron job to check for the mount and restart the service if it doesnt exist.
