### ISSUE TITLE
gmedia.mount

### ISSUE THREAD

**Issue by trippinshrumes** [animosity22/homescripts#15]
How does this file work in your system? When I attempt to start this I get that the file lacks ExecStart= and ExecStop= 

Thanks for any info you may be able to provide.

**Comment by animosity22** [comment]
Sorry as I missed the notification for this. This is just a standard systemd mount command and should start with:

systemctl start gmedia.mount

The .mount is the right extension on the file for it to work.

What operating system are you using?

**Comment by darkmount** [comment]
Note that the contents of `Where=` also dictates the name of this file. For example, if you had `Where=/mnt/disk0` the file would need to be named `mnt-disk0.mount` for it to work.

**Comment by animosity22** [comment]
That is correct as @darkmount mentioned. Thanks!
