### ISSUE TITLE
Why do you have a reference to cache?

### ISSUE THREAD

**Issue by EldonMcGuinness** [animosity22/homescripts#16]
https://github.com/animosity22/homescripts/blob/4ca802645a7ea2534935062354630811fd6a6119/rclone.conf#L15-L21

Is this section a carryover from a time when you used cache?

**Comment by animosity22** [comment]
Yep. I keep it for testing any cache stuff/questions that come up.

Cache has a good use case for Plex Music and if the players tend to open/close repeatedly, it would be good for that too.

**Comment by EldonMcGuinness** [comment]
Cheers, might be worth a comment in there to explain it :D

**Comment by animosity22** [comment]
Good idea! I added a few lines of comments for its use.
