### ISSUE TITLE
Setting order of systemd files

### ISSUE THREAD

**Issue by safusu** [animosity22/homescripts#17]
In the readme, it says that the order is as follows:

- rclone mount
- warm up cache
- mount mergefs

but the `gmedia.mount` file still starts after `gmedia-rclone.service` and `gmedia.find` starts after `gmedia.mount`

**Comment by animosity22** [comment]
Thanks. I was in the process of updating a bunch of stuff and must have left that order out.

It really doesn't matter on that as I changed the find to be a 'fire and forget' item so it normally takes 30 seconds or so to run and for boot, it can be that way.

Thanks for catching that as I think it's fixed now!

**Comment by safusu** [comment]
Thanks for the update, much appreciated!
