### ISSUE TITLE
Writing to the mergerfs mount uploads immediately

### ISSUE THREAD

**Issue by libussa** [animosity22/homescripts#18]
Whenever I write something in the mergerfs mount, it uploads it to drive... Any idea?

**Comment by animosity22** [comment]
What does your mergerfs mount look like?

```
root      1083     1  0 09:31 ?        00:00:51 mergerfs /data/local:/GD /gmedia -o rw,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,dev,suid
```
is mine so the order is key as /data/local is always written to first regardless.

**Comment by libussa** [comment]
this is mine 
` 2383 libussa    10 -10  393M  7588  1352 S  0.0  0.0  1:31.30 mergerfs /mnt/local:/mnt/crypt /mnt/media -o rw,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,dev,suid `

crypt is the rclone mount, /mnt/local is local. When I do `touch /mnt/media/test` it writes the file to the rclone mount :(

**Comment by animosity22** [comment]
What does this show?

```
[felix@gemini ~]$ mount | grep fuse
gcrypt: on /GD type fuse.rclone (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,allow_other)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
data/local:GD on /gmedia type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,allow_other)
```

**Comment by libussa** [comment]
```crypt: on /mnt/crypt type fuse.rclone (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,allow_other)
local:crypt on /mnt/media type fuse.mergerfs (rw,relatime,user_id=0,group_id=0,allow_other)
```

**Comment by animosity22** [comment]
Isn't your mount messed up as it only says "local" and not "/mnt/local"?

**Comment by animosity22** [comment]
You can always check with the mergerfs github as well as he's much more knowledgable than me if that didn't solve it.
