### ISSUE TITLE
mergerfs systemd

### ISSUE THREAD

**Issue by justlookingaround12** [animosity22/homescripts#19]
First of all, Great write up you have here! I'm not so good with this stuff and I managed to get farther than i expected without needing to open up an issue! Thanks so much

Regarding my issue, I just don't know how to "convert" your systemd file for mergerfs to be used on Ubuntu. I managed to get the rclone file working but I get a lot of error with the mergerfs:
1. Unknown section 'Mount'. ignoring.
2. Service lacks both ExecStart= and ExecStop= setting. Refusing
3. Finally this isn't an error (yet, I guess) but i read in another issue the the file name and the Where should match. My where is something like /home/test/Plex/"TV Shows". How would i name the file in this case?

Thanks again and I'd really appreciate some help

**Comment by animosity22** [comment]
The mergerfs one is a bit tough.

The mounted name has to match. I've only ever mounted /gmedia and not tried anything else so my mount command is named gmedia.mount

```
[felix@gemini system]$ cat gmedia.mount
[Unit]
Description = /gmedia MergerFS mount
After=gmedia-rclone.service
RequiresMountsFor=/data

[Mount]
What = /data/local:/GD
Where = /gmedia
Type = fuse.mergerfs
Options = defaults,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff

[Install]
WantedBy=multi-user.target
```
I think the #2 is because you have it called a .service rather than a .mount

If you share what you are trying to mount and your .mount script, I can help.

**Comment by justlookingaround12** [comment]
So right now I changed my Folder name to "TVShows" to at least get rid of that issue. 
I have also corrected the file and it's now called "home-rmount-mergerfs-TVShows.mount"
I am trying to mount my rclone - /home/rmount/GPlex/TV Shows to /home/rmount/mergerfs/TVShows
Here is what I have right now:

```
[Unit]
Description = MergerFS mount
After=rclone-mount.service
RequiresMountsFor=/home/rmount ### I also tried commenting this line out

[Mount]
What = /home/rmount/GPlex/'TV Shows'
Where = /home/rmount/mergerfs/TVShows
Type = fuse.mergerfs
Options = defaults,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff

[Install]
WantedBy=multi-user.target
```
I get the following error: fuse: missing mountpoint parameter

**Comment by animosity22** [comment]
I'm a little confused at what you are trying to do. 

Normally with mergerfs, you are putting 2 or more things together.

Is that not what you are trying to do?

Is mergerfs available on your system?

```
[felix@gemini system]$ which mergerfs
/usr/bin/mergerfs
```

**Comment by justlookingaround12** [comment]
I'm trying to put 2 things together but I think I'm just not understanding how to create the startup script for it. Or even just use mergerfs directly..
I have a directory, /home/plex/hdd/media, in this folder, i have "TV Shows" and "MOVIES". Those 2 folders are where sonarr/radarr will move files to once they downloaded. 
I would like to start each day with the contents of those 2 folders being placed into: /home/plex/GPlex (which itself also has "TV Shows" and "MOVIES". 
I really hope i managed to explain it correctly, please let me know how to move forward. 
My assumption after your reply is: 

```
[Unit]
Description = MergerFS mount
After=rclone-mount.service
RequiresMountsFor=/home/plex ### I have no idea what this does

[Mount]
What = /home/plex/GPlex
Where = /home/plex/hdd/media
Type = fuse.mergerfs
Options = defaults,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff

[Install]
WantedBy=multi-user.target
```

**Comment by animosity22** [comment]
I think if I'm following.

/home/plex/hdd/media
/home/plex/GPlex

Those are your two source directories.

In mergerfs speak, you'd make a 3rd item to mount it to and it would basically combine them.

So something like a 3rd mount called /combined

```
mergerfs /home/plex/hdd/media:home/plex/GPlex /combined -o rw,allow_other
```

You have to make some decisions on how you want the combined mount to act though. I use a first listed, always write to that first location policy. I'm not sure what your use case is or how you would want it to flow.

For me, I use a local mount and my rclone mount so I want everything to be written local first and I move it over night.

**Comment by justlookingaround12** [comment]
Yup you understand correctly. Also, my gdrive is the "GPlex" folder and my hdd/media folder is where sonarr/radarr move things once completed locally. I created a folder, ~/mergerfs that you called combined. 
Then, is this .mount file correct?

[Unit]
Description = MergerFS mount
After=rclone-mount.service
RequiresMountsFor=/home/plex/hdd ### I have no idea what this does

```
[Mount]
What = /home/plex/hdd/media:/home/plex/GPlex
Where = /home/plex/mergerfs
Type = fuse.mergerfs
Options = defaults,sync_read,auto_cache,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff

[Install]
WantedBy=multi-user.target
```

**Comment by animosity22** [comment]
That looks correct.

So that means everything will write to /home/plex/hdd/media first and in my setup, I would point everything to /home/plex/mergerfs in terms of Sonarr/Radarr/Plex/etc.

**Comment by justlookingaround12** [comment]
Thank you for your help, just for my sake of understanding, what is "RequiresMountsFor" doing in the systemd script?
