### ISSUE TITLE
Dont start Plex before Rclone and MergerFS are ready

### ISSUE THREAD

**Issue by krisnyse** [animosity22/homescripts#20]
Hi,

Running Plex in docker with your sweet config with rclone and MergerFS. I have a problem with the order my services start. If I reboot the server all media titles are marked as "unavailable" in Plex,  most likely because the rclone and mergerFS services were not started before Plex. If I restart the Plex docker container everything is back to normal. Would it be possible to change this config so Plex/Docker dont start before the rclone mount and mergerFS are ready?

**Comment by jjbrunton** [comment]
I have this exact issue.

**Comment by animosity22** [comment]
I've never hit that one personally.

You'd have to tweak your plexmediaserver.service to add in whatever your last service is called:

```
[Unit]
Description=Plex Media Server
After=network.target mergerfs.service

[Service]
EnvironmentFile=/etc/conf.d/plexmediaserver
ExecStart=/usr/lib/plexmediaserver/Plex\x20Media\x20Server
Type=simple
User=plex
Group=plex
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```

Or you could add  do a pre check on the mount point with an ExecPre command:

```
ExecStartPre=/bin/bash -c 'while [ ! -f /gmedia/mounted ]; do /usr/bin/sleep 5; done'
TimeoutStartSec=300
```

Couple ways to get that done as it depends more on systemd.

**Comment by jjbrunton** [comment]
This is specifically about docker, I imagine it would be easily achieved with systemd if it wasn't a docker setup.

**Comment by animosity22** [comment]
I am sorry as I don't use docker and have no familiarity with it so I don't think I could add much more.
