### ISSUE TITLE
Directory name collisions 

### ISSUE THREAD

**Issue by ArabCoders** [animosity22/homescripts#21]
Hi, 

Is there anyway using your setup to make directory names collisions list content from both mount points?

For example

1. /mnt/glocal has directory named "test123/" that has the following files 
* f1.txt
* f2.txt
* f3.txt

2. /mnt/gdrive has same directory named "test123/" that has the following files
* f4.txt
* f5.txt

when you run ```ls /mnt/storage/test123``` can mergerfs show the content of both instead of just the first one?

this really making mergerfs not possible for usage with currently running shows etc.

**Comment by animosity22** [comment]
You should see:

all 5 files under the directory as that's exactly what I do.

What is your config and what are you seeing when you do the ls?

```
[felix@gemini gmedia]$ cd test
[felix@gemini test]$ ls
hosts  test2
[felix@gemini test]$ ls /GD/test
hosts
[felix@gemini test]$ ls /data/local/test
test2
```

**Comment by ArabCoders** [comment]
Thanks for your quick reply, 

Right now this is my setup

```sh
rclone mount \
--allow-non-empty \
--allow-other \
--buffer-size 256M \
--cache-tmp-wait-time 5m \
--dir-cache-time 72h \
--drive-chunk-size 32M \
--fast-list \
--log-level INFO \
--log-file ~/my_scripts/rclone.log \
--poll-interval 5m \
--size-only \
--timeout 1h \
--tpslimit 10 \
--vfs-read-chunk-size 128M \
--vfs-read-chunk-size-limit off \
gcrypt: ~/mnt/gdrive
```

````sh
mergerfs -o defaults,allow_other ~/media:~/mnt/gdrive ~/mnt/storage
````
both ~/media and ~/mnt/gdrive has the following folders "F1, F2, F3" and extra folder "F4" on ~/mnt/gdrive

when i go to ~/mnt/storage and 'ls'

it's correctly show all 4 folders. However when i go to say F1 it ONLY show folders/files from first mounted path in this case ~/media

im really at loss here, i've spend 6hrs trying to figure out why is that happening

**Comment by animosity22** [comment]
Can you get rid of the ~ and use the full paths?

Can you share the ls of each one like I did above and share a ps -ef | grep mergerfs

```
[felix@gemini system]$ ps -ef | grep merger
felix    10158  5983  0 20:17 pts/0    00:00:00 grep merger
root     28094     1  1 Jul26 ?        00:57:50 mergerfs /data/local:/GD /gmedia -o rw,async_read=false,use_ino,allow_other,auto_cache,func.getattr=newest,category.action=all,category.create=ff,dev,suid
[felix@gemini system]$
```

**Comment by ArabCoders** [comment]
Holy holy, thank you very much, like i feel so dumb right now. indeed mergerfs wasn't translating ~/ correctly for 2nd mount point. as soon as i changed them to full path they started showing correctly.

Thank you very much.

**Comment by animosity22** [comment]
Nice!

What are you trying to do? They are a ton of policies and was to configure that part so it can do what you are looking for. I use always write to the first disk, which is my local disk and I keep my rclone mount read/write so I can delete/upgrade media if needed.

**Comment by ArabCoders** [comment]
Yeah, I pretty much has the same setup as you

/mnt/gdrive is the google drive.
/torrents/data where data gets downloaded.
/media/{TV,Movies,Anime} where things get sorted by filebot.
/mnt/storage is just for plex so i dont overuse api calls.

**Comment by animosity22** [comment]
So I use "category.create=ff" to write always to the first disk which is my /data/local.

**Comment by ArabCoders** [comment]
i see, do you have good way for plex to auto pick up the changes to library instead of having to rescan?

**Comment by animosity22** [comment]
You have a few options. 

I use Sonarr/Radarr plugged into Plex so it notifies Plex for a scan. You can use something like plex_autoscan which can do similar and also can monitor for changes on GD.

https://github.com/l3uddz/plex_autoscan

**Comment by ArabCoders** [comment]
Thanks sadly my host does not give me direct access to plex to use plex_autoscan

**Comment by animosity22** [comment]
I'll close this out as the original issue was solved and good luck with your provider!
