### ISSUE TITLE
Mergerfs slow 

### ISSUE THREAD

**Issue by Cookiezzz** [animosity22/homescripts#22]
Heya,

I'm using your scripts to mount my data onto a VPS.
I've got an issue with the mergerfs mount on the account of it being slow.
Before going to the mergerfs github thought maybe I'd ask you.

So I have 3 mounts.
/mnt/local -> SMB mounted local freenas server
/mnt/gdrive -> gdrive rclone mount
/mnt/media ->mergerfs mount.

Whenever I'm accessing the local or gdrive mount, it's working fine.

Whenever accessing the media mount however, it feels really slow.
Take the 'ls' command as an example.

`time ls local/movies/
real    0m0.435s
user    0m0.011s
sys     0m0.024s
`
`
time ls gdrive/movies/
real    0m0.039s
user    0m0.002s
sys     0m0.012s
`
` time ls media/movies/
real    0m58.655s
user    0m0.022s
sys     0m0.069s`

For some reason executing that on my mergerfs mount takes ages.
I believe this is also why I'm having radarr problems (It being really really slow)

My mergerfs mount.

```
[Unit]
Description = /mnt/media MergerFS mount
After=rclone.service
RequiresMountsFor=/mnt/local

[Mount]
What = /mnt/gdrive/:/mnt/local/
Where = /mnt/media
Type = fuse.mergerfs
Options = async_read=false,use_ino,allow_other,auto_cache,func.getattr=newest,category.action=all,category.create=ff

[Install]
WantedBy=multi-user.target
```

My rclone config.
```
[GD]
type = drive
client_id = xxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxx
scope = drive
token = {"access_token":"xxxxxxxxxxxxx"}

[GC]
type = cache
remote = GD:googledrive
chunk_size = 10M
info_age = 1d
chunk_total_size = 10G

[GCrypt]
type = crypt
remote = GC:
filename_encryption = standard
directory_name_encryption = true
password = xxxxxxxxx
password2 = xxxxxxxxxx
```

Rclone service for info.
```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/Cookiezzz/.config/rclone/rclone.conf

ExecStart=/usr/bin/rclone mount GCrypt: /mnt/gdrive \
--allow-other \
--transfers 2 \
--buffer-size 1G \
--dir-cache-time 24h \
--log-level INFO \
--log-file /home/Cookiezzz/.config/rclone/rclone.log \
--timeout 1h \
--gid 1003 \
--umask 002 \
--user-agent lunarhostingapp \
--rc
ExecStop=/bin/fusermount -uz /mnt/gdrive
Restart=on-failure
User=Cookiezzz
Group=Cookiezzz
```

Could you perhaps try an ls on your system? See if it has the same problem.

**Comment by animosity22** [comment]
transfers does nothing on a mount so you can remove it.

How many files and folders do you have?

```
31862
[felix@gemini GD]$ find . -type d | wc -l
2946
[felix@gemini GD]$ find . -type f | wc -l
28916
```

**Comment by Cookiezzz** [comment]
I added the time command so you can see how long it actually takes.
I have another server at home, which also has the rclone mount, same smb share and there it takes near to no time. It's the last one.

I'm starting to think it's because i've mounted my home SMB storage over the internet on my VPS.
ls /mnt/local works fast, but the find command does not. Perhaps the ls command is being cached somehow..
Probably not a mergerfs problem, just my annoying setup.. Thanks tho!
```
[Cookiezzz@hetzner media]$ time find . -type d | wc -l
1057

real    3m54.033s
user    0m0.097s
sys     0m0.249s
```
```
[Cookiezzz@hetzner media]$ time find . -type f | wc -l
5333

real    3m2.125s
user    0m0.140s
sys     0m0.237s
```
```
[Cookiezzz@hetzner media]$ mergerfs -V
mergerfs version: 2.28.1
FUSE library version: 2.9.7-mergerfs_2.28.0
fusermount version: 2.9.2
using FUSE kernel interface version 7.29
```

```
time find . -type d | wc -l
1057

real    0m2.057s
user    0m0.015s
sys     0m0.066s


```

**Comment by animosity22** [comment]
I think you are correct as it seems to be tied to that one mount being slow. I'm not sure at all how mergerfs deals with the SMB issue. Might be wise to try the mergerfs github as your setup is definitely much different than mine.
