### ISSUE TITLE
Mergerfs and auto_cache

### ISSUE THREAD

**Issue by safusu** [animosity22/homescripts#23]
Per the mount options as of 2.28.1:

* **auto_cache**: deprecated - Invalidate data cache if file mtime or size change. Use `cache.files=auto-full` instead. (default: false)

Not sure what the harm of leaving auto_cache on in gmedia.mount is, but I've replaced it with the recommended change and saw no adverse affect for now.

**Comment by animosity22** [comment]
Thanks!

I made the change myself and updated my gmedia.mount.

Much appreciated!
