### ISSUE TITLE
A little question regarding the upload script

### ISSUE THREAD

**Issue by kSotin** [animosity22/homescripts#25]
According to your description, I assume that the nightly upload is processed at fixed time each day. So there’s a small question that is confusing me, about the potential conflict during the upload. Is it necessary to take into consideration that when uploading, other apps, say, Plex/Radarr/Sonarr, etc. might be reading the files that are being uploaded, and as these files are being moved from local to remote cloud, it would cause some errors? Or it is totally unnecessary to worry as some mechanisms within mergerfs would have them all handled?

**Comment by animosity22** [comment]
There is a 10-15 second window when that could be a problem, but in all the time I've been running it, I've never hit an issue. I wouldn't worry about it.

I run it at off peak times at like 2am.

**Comment by kennyparsons** [comment]
Can confirm. No issues here with mine either. Plus, if a file does change in that time, I've seen rclone recognize it and reattempt to process it.
