### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by iodides** [animosity22/homescripts#26]
Where did you put the new file?
local folder? or merged folder?

when I moved a file to local folder, plex does not check new file added. file moved immediately.

when I moved a file to merged folder, plex catched new file add. but file moved slowly

**Comment by animosity22** [comment]
Everything always goes to the mergerfs setup folder for me.

I have /gmedia as my mergerfs and everything points to that.

Underneath of that:

/gmedia
 - /local - my local disk which is written to first
 - /GD which my gmedia mount

At night, I have an upload script from /local that moves from local disk to GD and rclone pick that up via polling every 10 seconds. The absolute worst case is a file missing 10 seconds but for me, it's never happened and I have no issues as I do my moves at 3am.
