### ISSUE TITLE
fuse: unknown option `async_read=false'

### ISSUE THREAD

**Issue by jscottdouglas** [animosity22/homescripts#27]
I've looked all over but I am getting this error when trying to use your mergerfs service, i couldn't find how to fix this error even looked at mergerfs git

$ mergerfs --version
mergerfs version: 2.24.2
FUSE library version: 2.9.8-mergerfs
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

/etc/fuse.conf has allow_other available

any help on fixing this issue would be great.

command in service file i am using:

/usr/bin/mergerfs /diskpool/local:/diskpool/google /diskpool/cloud -o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true

**Comment by animosity22** [comment]
You just have an old version and would need to install the latest:

```
mergerfs version: 2.28.3
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount3 version: 3.4.1
using FUSE kernel interface version 7.29
```

You can find the one I am using here:

https://github.com/trapexit/mergerfs/releases

He has a section on his github on building/installing:

https://github.com/trapexit/mergerfs#building

**Comment by jscottdouglas** [comment]
thanks
