### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by qarth** [animosity22/homescripts#29]
Just letting you know that you've pushed your api key, email and domain info to github in the caddy.service file. Not sure that's a good idea.

**Comment by animosity22** [comment]
Oh man. Thanks! Sometimes I try to put things up and I do mess up unfortunately!

Much appreciated and I'll fix that.

**Comment by animosity22** [comment]
Thanks. I removed the old API key that I just changed. Much much appreciated!!!
