### ISSUE TITLE
Install http.login directive post caddy install

### ISSUE THREAD

**Issue by kennyparsons** [animosity22/homescripts#30]
I've had Caddy installed for a long time, and I'd like the use jwt/login directives. How do i install them after i've already installed caddy?

**Comment by animosity22** [comment]
I install with this option as you can just re-install the latest with the plugins that you use:

```
CADDY_TELEMETRY=on curl https://getcaddy.com | bash -s personal http.cache,http.cgi,http.jwt,http.login,http.realip,tls.dns.cloudflare

```

**Comment by kennyparsons** [comment]
@animosity22 Do you know if you'll try to switch to caddyv2? Caddyv1 might be dropping support for tls1.1 soon. I looked into the caddyv2 jwt and login middlewares. There might be some activity on porting them over.

**Comment by animosity22** [comment]
I'm waiting for a full release of v2 to come out as it's only a RC at the moment. I'll take a look once that releases and update what's needed.
