### ISSUE TITLE
Team drive and service accounts

### ISSUE THREAD

**Issue by kiityman1** [animosity22/homescripts#31]
Hello, do you happen to have a script to utilize team drives and service accounts to bypass the 750gb limit?

**Comment by animosity22** [comment]
100% no as I don't think that's a good idea to get around those limits.

**Comment by kiityman1** [comment]
Any specific reason? Sorry to bother you again

I currently use cloudbox to upload 10+ tb daily so it is very useful

I don't see any issue with it, no worse then normal drive

**Comment by mkeguy106** [comment]
You upload 10TB+ daily?  Man, you're gonna ruin gsuite for the rest of us.  Don't try to abuse the service.

**Comment by kiityman1** [comment]
Sometimes. It's not "ruining" gsuite. Everyone using gsuite to store **pirated** movies is "abusing" it.

**Comment by kiityman1** [comment]
> You upload 10TB+ daily? Man, you're gonna ruin gsuite for the rest of us. Don't try to abuse the service.

Sometimes. It's not "ruining" gsuite. Everyone using gsuite to store **pirated** movies is "abusing" it.
