### ISSUE TITLE
How to use openvpn for some traffic, but not all

### ISSUE THREAD

**Issue by kennyparsons** [animosity22/homescripts#32]
From your setup, it looks like only some traffic is configured to go through the vpn. Is it possible to have open vpn connected but not route all traffic through it? I only want some traffic, such a wget for example to use it, and I only want it to use it at specific times (when wget-ing from open directories, for example).

**Comment by animosity22** [comment]
Yep. I used this article to setup my split tunnel VPN so one user goes through the VPN only. You can also force things out an interface depending on the command:

https://www.htpcguides.com/force-torrent-traffic-vpn-split-tunnel-debian-8-ubuntu-16-04/

**Comment by kennyparsons** [comment]
@animosity22 thanks. I'm currently running an openvpn server via docker, but i know you dont run docker. I'll try the htpcguide way on vm first.

**Comment by Dulanic** [comment]
I use my own VPN container and link them.
https://github.com/Dulanic/ovpn

**Comment by animosity22** [comment]
Yep, that makes sense. Let me know if you have any more questions and I can try to help out.
