### ISSUE TITLE
Make larger rclone cache?

### ISSUE THREAD

**Issue by kiityman1** [animosity22/homescripts#33]
Hello! I setup your scripts but unfortunately Plex is taking about 20 seconds to start a stream. I wondering if you know any better mount settings which will speed this up?

**Comment by kennyparsons** [comment]
@kiityman1 post your logs/provide a little more detail? Also what's your bandwidth. There's a ton of factors that could cause a slow load.

**Comment by animosity22** [comment]
I'm not sure what you mean as I don't use the cache backend at all. Can you be more specific on what your setup is and what you are using?

**Comment by animosity22** [comment]
If you have any questions, just post on https://forums.rclone.org and I'm happy to help out.
