### ISSUE TITLE
mergerfs service file name?

### ISSUE THREAD

**Issue by shawnp0wers** [animosity22/homescripts#36]
I'm trying really hard to understand this:

> This needs to be named the same as the mount point for the mount to work properly. I use /gmedia so the file is named accordingly.

But for the life of me I can't. Is it a bug in mergerfs or something, and if so, how does mergerfs even know?

**Comment by animosity22** [comment]
The service file name needs to be the same as the mount point name.

What's the actual problem you are seeing?

**Comment by shawnp0wers** [comment]
I'm not seeing a problem, lol. I just couldn't figure out why it had to be named that. I had already set up mergerfs, but my file is named mergerfs.service (because I have no imagination) -- then I read your instructions and couldn't figure out what the issue was I might be missing. :)

**Comment by animosity22** [comment]
Oh I see now. That's old I used to use a .mount service file which the where has to match the .mount name. I need to fix that. Thanks for asking!

**Comment by shawnp0wers** [comment]
Oh cool, I'm glad I'm not missing something! Thanks for clarifying. :)
