### ISSUE TITLE
upload script deleted my whole online storage. Lost 30 TB

### ISSUE THREAD

**Issue by DerUntote** [animosity22/homescripts#39]
Hi,

please warn people by setup your script collections.

- I made a mergerfs + rclone setup 
- run upload_cloud on my mergerfs storage

-> alle files where deleted and i lost all my gdrive files.

I dont know why yet, but it seems that the mergerfs example we used here where didnt readonly on the online storage.

-o **rw**,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true

**if you are reading directly from your rclone mount, you do not need to worry about any of the mergerfs settings**

I had worries ;- )

**Comment by DerUntote** [comment]
/usr/bin/rclone move /home/luke/media/ gd-crypt: --log-file /opt/rclone/logs/upload.lo-dirs --fast-list --drive-stop-on-upload-limit


luke@home:~/git/homescripts/scripts$ cat /opt/rclone/logs/upload.log
2020/06/14 21:28:36 Failed to load filters: open /opt/rclone/scripts/excludes: no such
2020/06/14 21:45:15 INFO  : 1GB.bin: Deleted
2020/06/14 21:45:16 INFO  : folder/100MB.bin: Deleted
2020/06/14 21:45:16 INFO  : folder2/100MB.bin: Deleted
2020/06/14 21:45:17 INFO  : folder3/100MB.bin: Deleted
2020/06/14 21:45:17 INFO  : folder4/100MB.bin: Deleted
[tousend lines that something got deleted]

**Comment by animosity22** [comment]
I'm sorry but I'm not following as my setup isn't supposed to be read only as you can't upgrade media on a read only drive so I use read/write on purpose.

There isn't anything about my scripts that 'deletes your entire' library. 



> /usr/bin/rclone move /home/luke/media/ gd-crypt: --log-file /opt/rclone/logs/upload.lo-dirs --fast-list --drive-stop-on-upload-limit

The worst that happens with a missing include is you upload to your cloud remote so again, nothing lost as it only deletes once it's on the remote.

So what am I warning people about?

**Comment by animosity22** [comment]
Also for information, if the exclude file is missing, the rclone command does not run:

It exits out and runs no rclone command:

```
felix@gemini:~$ rclone move /home/felix/test GD:test -vv --exclude-from nothere
2020/06/15 10:18:20 Failed to load filters: open nothere: no such file or directory
```

If you want to share what you modified and what you ran, I'm happy to help, but nothing from my repo would delete your remote contents as it only uploads local to remote.

If you can show me something that would, I'm happy to help and fix the issue but I'm not seeing any issue like that.

**Comment by DerUntote** [comment]
I found out whats wrong. The upload script says /local but i uploaded /gmedia

**Comment by animosity22** [comment]
So yeah, that would definitely cause an issue.

You moved from the same drive to the same drive and at the end of the move, it deletes the source.

```
2020/06/15 13:40:00 DEBUG : rclone: Version "v1.52.1" starting with parameters ["rclone" "move" "/gmedia/hosts" "gcrypt:" "-vv"]
2020/06/15 13:40:00 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/06/15 13:40:00 DEBUG : fs cache: renaming cache item "/gmedia/hosts" to be canonical "/gmedia"
2020/06/15 13:40:01 DEBUG : hosts: Size and modification time the same (differ by 0s, within tolerance 1ms)
2020/06/15 13:40:01 DEBUG : hosts: Unchanged skipping
2020/06/15 13:40:01 INFO  : hosts: Deleted
2020/06/15 13:40:01 INFO  :
```

and hosts is gone from my /gmedia and my remote since they are one in the same.

**Comment by DerUntote** [comment]
time to playi n the backup : - )

**Comment by animosity22** [comment]
To help out, I'll add a few more comments and I can think about how to put a few checks in to validate the move is actually a local file system. 

Good luck as there isn't much I can do to fix that mistake.

**Comment by kennyparsons** [comment]
@DerUntote you can try browsing the google drive trash. https://rclone.org/drive/#drive-trashed-only

**Comment by animosity22** [comment]
Hopefully as @kennyparsons  mentioned you have it in the trash.

To prevent it from again, I used my poor bash skills and added a check to make sure LOCAL is actually a local file system and added some wording / warning for folks as that move loop is definitely bad!

**Comment by Cringely** [comment]
You can also browse and restore trashed items from the drive gui at drive.google.com

![image](https://user-images.githubusercontent.com/759077/84821859-a71d6000-afd0-11ea-8882-cb1f00316466.png)
