### ISSUE TITLE
Upload Script

### ISSUE THREAD

**Issue by peewee5** [animosity22/homescripts#4]
I have one additional question about your upload script. Is the lockfile that you create in the script what allows you to run another rclone command while you have GD mounted? Also, do you notice a performance difference in your video files being read by Plex if they are in individual folders vs all in the same folder? Thanks again.

**Comment by animosity22** [comment]
The reason for the lockfile is that you don't wan to run multiple uploads from the same local source at the same time. I only run once a night so the odds of an upload not finishing before the next is started is rare, but figured I'd put a lockfile in there to ensure I don't get multiple copies running at the same time.

This would be more useful if you ran it hourly or something like that so it wouldn't step on itself. The rclone mount is independent from my upload script there isn't any contention or problem there.

The reason I was having a few folders was more related back to a directory listing. Rclone has to do an API call for each directory you have so having 1000 directories, it makes 1000 API calls / 1 for each directory.

To reduce that, I have movies that I consider 'done' so I remove them from Radarr and just dump them into a folder. I'll probably having 1000 movies per folder or something to help break it up a little, but Plex doesn't care either way for playing. This is only supported from a plex level for Movies as TV Shows each require their own folder based on Plex's naming standards.

Let me know if anything isn't clear :)

**Comment by peewee5** [comment]
> The rclone mount is independent from my upload script there isn't any contention or problem there.

I'm still a little unclear on this because every time that I have my rclone google drive mounted and try and run any command to move something to or retrieve something from it, I get this error:

ERROR : /home/michael/.cache/rclone/cache-backend/sotcache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/michael/.cache/rclone/cache-backend/sotcache.db": timeout

Am I just doing something wrong on my end or do I need another remote that I'm unaware of?

**Comment by animosity22** [comment]
Oh, yes, you can't run multiple cache backends in your rclone.conf.

You could just make another entry in your rclone.conf that is a duplicate basically if you want to run another cache backend or you could just use regular crypt backend for GD instead. 

My rclone conf is posted earlier today so you can see what mine is as it's straight forward.

**Comment by peewee5** [comment]
I just realized the issue with the cache backends as I was writing it lol.  I was just taking a look at your rclone.conf and I'm a little unsure what the second crypt drive is for where you have the remote as gcache. (Sorry for all of the questions, this has stumped me fore the longest time so I'm really trying to get it working right now)

**Comment by animosity22** [comment]
My GD entry is my top level Google Drive.
My gcrypt entry is the encrypted folder inside of my Google Drive that has my plex media

I mount gcrypt when I'm using vfs-read over the cache backend

If I was using the cache backend, my root GD is still my top level google drive.
You have to cache before you decrypt so I have a "gcache" pointing to the encrypted folder in the root of my Google Drive which points back to GD:media 
Finally, I have to decrypt the cached entry so I "gmedia" is the decrypt of the cached entry in my rclone.conf


Probably gets confusing because I mount it to /gmedia regardless if it's cache or not.

**Comment by animosity22** [comment]
Any other questions, just let me know!
