### ISSUE TITLE
Why is async set to false removed from the service?

### ISSUE THREAD

**Issue by sevospl** [animosity22/homescripts#40]
I read the changelog and saw that you tested it with the latest version of rclone and it's proven to not cause any spike in IOwait - but it was the complete opposite for me; it's still a thing.

Probably while testing you didn't have anything much going on at that time, but when at least few people streaming and something else (uploading etc.), IOwait goes up to 8-10% and CPU usage is very high (at least 50%). Once got back to async being set to false, it all went back to normalcy (barely see any rclone processes as they barely use any resources).

Even [ncw admitted](https://forum.rclone.org/t/rclone-1-52-release/16718/17) that v1.52 still suffers this severe bug and in order to get rid of the IOwait it's still necessary to have `--async-read=false`. 

So I would suggest adding it back as it's still not entirely fixed.

**Comment by animosity22** [comment]
Do you see any issues in your logs ?

My IO Wait pattern has not changed at all really when I turned it off:

![image](https://user-images.githubusercontent.com/5088712/84937396-ac9aa900-b0a9-11ea-9eeb-135199402c1a.png)

**Comment by sevospl** [comment]
To be honest, I don't have logs for statistics for IOwait over a certain period of time. I simply check it with glances randomly, from time to time, and it usually had a spike in IOwait with rclone v1.52. Once I added back the `-async-read=false` and it's all good now again (haven't come across IOwait higher than 0.5%). 

What kind of software are you using? I'll give it a go and compare both - one day with the flag and one day without it. :)

**Comment by animosity22** [comment]
My setup is a bit as I use netdata -> influxdb -> grafana. The grafana visualization is what you see pasted in.

netdata would give you a brief idea over a short period of time.

IOWait isn't bad. If you see errors in the rclone logs, I'm imagine that might be something.

**Comment by animosity22** [comment]
I've let this run for a number of days and I am seeing generally better performance with async reads as I get pretty much the same IOWait for me. If you find anything else, let me know.
