### ISSUE TITLE
Caddy 2.0

### ISSUE THREAD

**Issue by efaden** [animosity22/homescripts#41]
Any chance your going to update to Caddy 2.0?

**Comment by animosity22** [comment]
I do plan to at some point as when I first checked, the Google Auth stuff wasn't there. I will probably spend some time this week and check again as I was waiting for it 2.1 release to hit as it looks close.

**Comment by efaden** [comment]
Can't wait.  I have a similar setup and have been debating traefik vs caddy.  Caddy just seems easier for this, if only 2.0 had all of the functionality.

**Comment by animosity22** [comment]
I would just use v1 for now. 

I've been checking so it doesn't seem oAuth or CloudFlare realip plugins are out yet so I can't do much until they have what I want converted.

**Comment by efaden** [comment]
Sounds good.  I'll stick with 1.0

**Comment by Dulanic** [comment]
You can do it in other ways, but real ip has been ported to v2. Also, OAuth is supported.

https://github.com/kirsch33/realip
https://github.com/greenpau/caddy-auth-portal

**Comment by animosity22** [comment]
Nice! I'll check that out too. I need more time in the day.

**Comment by animosity22** [comment]
Thanks very much to @Dulanic as I converted everything tonight and I'm going to test a bit before I push a change up.

**Comment by animosity22** [comment]
I updated my proxy page as things seem to work fine. Let me know if you see anything wrong or whatnot and I'll close this out as done!

**Comment by animosity22** [comment]
Proxy information is updated so closing this out as it's done.
