### ISSUE TITLE
rclone --min-age uploads files too early

### ISSUE THREAD

**Issue by ativersum** [animosity22/homescripts#42]
i noticed that rclone uploads files to my gdrive that are younger than 3 days. 

according to this [post ](https://forum.rclone.org/t/min-age-created-time-or-modtime/11767/2) rclone uses last modified time and when i download an older tv show/movie that file is moved to gdrive on the same day.

**Comment by animosity22** [comment]
Yes, that's how it works.

I'd surmise you are using Sonarr or Radarr to change times on files as I have that off as I don't want to change the files.

![image](https://user-images.githubusercontent.com/5088712/85947520-3d2e8000-b919-11ea-9a5a-344b51286bfe.png)

**Comment by animosity22** [comment]
Let me know if you have any other questions.

Thanks!
