### ISSUE TITLE
vfs-cache-max-size question

### ISSUE THREAD

**Issue by thejck** [animosity22/homescripts#48]
You have --vfs-cache-max-size set to 500GB and your cache folder is /cache which I assume is on your SSD per your readme.
How does this work if your main drive is only 250Gb?

https://github.com/animosity22/homescripts/blob/master/systemd/rclone.service#L37

Sorry for opening this issue. let me know if you prefer a different method of communication

**Comment by animosity22** [comment]
I updated the readme to add in the 1TB SSD I use for my disk cache. I bought that when the new rclone release came out.

**Comment by thejck** [comment]
awesome. i just bought a 1tb ssd as well and was hoping for this answer. Do you leave this ssd dedicated for cache? Also how do you manage your plex transcode folder? I was thinking of letting it sit on this drive as well?

**Comment by animosity22** [comment]
I moved both my rclone cache and my plex DB install to that 'cache' disk.

I use an override for that:

![image](https://user-images.githubusercontent.com/5088712/96132192-1ac07280-0ec8-11eb-9a50-b6e106833471.png)

**Comment by rammellzee** [comment]
Do you believe the SSD is important if I'm only going to be reading off the mount?

**Comment by animosity22** [comment]
Nope, I seriously doubt need SSD speed. I just went overkill.

**Comment by animosity22** [comment]
Closing this out as I think I answered everything.
