### ISSUE TITLE
NC Flag mergerfs Gdrive

### ISSUE THREAD

**Issue by doob187** [animosity22/homescripts#49]
https://github.com/animosity22/homescripts/blob/523c5dfb41b7c3c066b6a4180964460511509ccc/systemd/gmedia.service#L8

set Google mount to :NC flag 

https://github.com/trapexit/mergerfs#branch-type

change to 

ExecStart=/usr/bin/mergerfs /local:/GD=RW:/gmedia=NC -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full

**Comment by animosity22** [comment]
I delete from my mount when media is upgraded which is why it is writable.
