### ISSUE TITLE
Show known working version numbers for applications

### ISSUE THREAD

**Issue by EldonMcGuinness** [animosity22/homescripts#51]
It might be a good idea to have a requirements.txt or something similar to document the versions of the applications you are using so people can make sure they can replicate it. A great example of this is rclone as only the beta supports some of the options you're using.

**Comment by animosity22** [comment]
I'm not using the beta so which option are  you talking about?

**Comment by EldonMcGuinness** [comment]
--rc-no-auth was one that I had issue with, I am running this on a stock 20.04 Ubuntu server build and installed rclone from the rclone [website](curl https://rclone.org/install.sh | sudo bash
) yesterday. That option would throw an error when you try to start the service. Beta took the option just fine.

**Comment by animosity22** [comment]
You'd have something else as with the current stable, it works fine.

```
felix@gemini:~$ rclone version
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5
felix@gemini:~$ rclone mount gcrypt: /home/felix/test --rc --rc-addr 127.0.0.1:5573 --rc-no-auth -vv
2020/11/28 20:57:59 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "mount" "gcrypt:" "/home/felix/test" "--rc" "--rc-addr" "127.0.0.1:5573" "--rc-no-auth" "-vv"]
2020/11/28 20:57:59 INFO  : Using --user felix --pass XXXX as authenticated user
2020/11/28 20:57:59 NOTICE: Serving remote control on http://127.0.0.1:5573/
2020/11/28 20:57:59 DEBUG : Creating backend with remote "gcrypt:"
2020/11/28 20:57:59 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/11/28 20:57:59 DEBUG : Creating backend with remote "GD:crypt"
2020/11/28 20:58:00 DEBUG : Encrypted drive 'gcrypt:': Mounting on "/home/felix/test"
2020/11/28 20:58:00 DEBUG : : Root:
2020/11/28 20:58:00 DEBUG : : >Root: node=/, err=<nil>
```

**Comment by EldonMcGuinness** [comment]
Interesting, I guess there is some way that an older cached version was served by rclone, or perhaps my server host had it cached/proxied somehow. That being said, a version number would have put that issue to be real quick. 

Again, just a suggestion. 👍

**Comment by animosity22** [comment]
I tend to avoid a version number as I hate to keep updating it. I'll add some verbiage to run the latest stable version as that's generally my settings. Appreciate the feedback as always.
