### ISSUE TITLE
Plex Scanner with GDrive

### ISSUE THREAD

**Issue by Tawagot0** [animosity22/homescripts#52]
Hello, using your 2 services for rclone and mergerfs I have read several times that you use plex_autoscan is this always the case?
Autoscan seems better to me because it uses the Plex API while Plex Autoscan uses CLI and does not allow Plex Push Notifications (which I am looking for because I have a crypt driver and autoscan does not use rclone).
Do you have the "Partial Scan" option checked on Plex, I don't know if it would explode the number of queries for Google if it's not the case it would allow me to use Push Notifications.

Thanks in advance!

**Comment by animosity22** [comment]
I'm not quite sure what you are asking or what problem you are try to solve.

With Google, you have 1 billion API hits per day so you aren't going to run out.

Partial Scan doesn't really matter either way if it's on or off.

Using autoscan is really up to you. If you think it works for your use case, use it. 

I don't know what a crypt driver is so not sure what that means.
