### ISSUE TITLE
scripts seems not working properly for a remote WITHOUT polling support

### ISSUE THREAD

**Issue by sm0kingm4n** [animosity22/homescripts#55]
I want to ask if there are any suitable workarounds for your wonderful scripts/configs to properly work when the remote (in my case jottacloud and my  homenas drive pool served via rclone sftp to my vps) **DOESN'T support drive polling**. I noticed file inconsistency and the need to remount periodically to get my files updated.

**> relevant rclone.service commands:** 
```
/usr/bin/rclone mount localbox: /mnt/rclone --allow-other --dir-cache-time 1000h --log-level INFO --log-file /var/log/rclone.log --poll-interval 15s --umask 002 --user-agent randomappname101 --rc --rc-addr :5572 --rc-no-auth --cache-dir=/cache --vfs-cache-mode full --vfs-cache-max-size 10G --vfs-cache-max-age 4h
ExecStop=/bin/fusermount -uz /mnt/rclone
ExecStartPost=/usr/bin/rclone rc vfs/refresh --fast-list recursive=true --rc-addr 127.0.0.1:5572 _async=false
```
**> relevant rclone.conf**
```
[localbox]
type = sftp
host = www.domain.com
user = user
port = 2022
pass = password
use_insecure_cipher = false
md5sum_command = md5sum
sha1sum_command = sha1sum
```

any help will be gratefully appreciated

**Comment by animosity22** [comment]
You'd have to run something else if you are not using Google Drive or a polling remote.

My setup is supporting specifically my use case.

For a non polling remote, you'd have to figure something else out.

```
# Google Drive is a polling remote so this value can be set very high and any changes are detected via polling.
--dir-cache-time 1000h \
```

With a non polling remote, you'd have to supply a lower dir-cache or refresh the cache when changes happen on your remote depending on how you would identify changes happneing.

**Comment by sm0kingm4n** [comment]
my use case it's very similar to yours (VPS serving media files via Jellyfin). I would like to tweak your scripts to suit my need.
> reduce or remove --dir-cache-time ?
> how to refresh cache every eg. 15-30 mins?
> how to enable sufficent cache formy media server to "preload" video files to avoid playback buffering-waiting? 
 I am open to any suggestions to modify the scripts accordingly. Thanks.

**Comment by animosity22** [comment]
> reduce or remove --dir-cache-time ?

That's up to you as whatever value you want to use as it would define how long you wait for something to show up.



> how to enable sufficent cache formy media server to "preload" video files to avoid playback buffering-waiting?

I use vfs-cache-mode full for this.



> I am open to any suggestions to modify the scripts accordingly. Thanks.

I have no plans to make any changes to my scripts to support non polling remotes as I am not looking to maintain that.

**Comment by sm0kingm4n** [comment]
thanks for your great work I understand so please tell me:
1) except for google drive which other remotes supports polling? 
2) any link or useful resources to hints and discussions about configure rclone to non polling remotes will be just great!

**Comment by animosity22** [comment]
> 1. except for google drive which other remotes supports polling?

I'm unaware of a list of all the remotes and if they support polling. You'd probably want to check the remote documentation and see what's there.



> 2\. any link or useful resources to hints and discussions about configure rclone to non polling remotes will be just great!

I'd probably search on the forums https://forum.rclone.org

I only use Google Drive as that's my use case.

**Comment by animosity22** [comment]
Closing this item out as I answered what I could and you'd might have some better luck on the forums with folks that perhaps use that backend. 

Good luck!
