### ISSUE TITLE
Trouble with atomic moves

### ISSUE THREAD

**Issue by g4m3r7ag** [animosity22/homescripts#61]
Atomic moves currently aren't working when Sonarr/Radarr are importing. I'm curious of your download directory structure in NZBGet and if atomic moves are working for you? 

My current setup is 
SMB Mount to NAS
```
//192.168.6.1/SSD_Data/ /mnt/VMdata/ cifs credentials=/home/user/.smbcredentials2,vers=3.0,iocharset=utf8,uid=user,gid=user 0 0
```
Rclone mount
```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/user/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount m_crypt: /mnt/m_crypt/ \
--allow-other \
--buffer-size 128M \
--dir-cache-time 1000h \
--log-level INFO \
--log-file /opt/rclone/logs/rclone.log \
--poll-interval 15s \
--timeout 1h \
--umask 002 \
--rc \
--rc-addr=127.0.0.1:5791
ExecStop=/bin/fusermount -uz /mnt/m_crypt/
Restart=on-failure
User=user

[Install]
WantedBy=multi-user.target
```
MergerFS mount
```
[Unit]
Description = /media MergerFS mount
Requires=mcryptmount.service
After=mcryptmount.service
RequiresMountsFor=/mnt/VMdata/
RequiresMountsFor=/mnt/m_crypt/

[Service]
Type=forking
ExecStart=/usr/bin/mergerfs /mnt/VMdata/Downloads/TempMedia:/mnt/m_crypt/ /mnt/media -o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
On all of my containers I pass /mnt to /mnt in the container 
```
        volumes:
            - /docker-data/dl-stack/sonarr:/config
            - /mnt:/mnt
```

NZBGet currently downloads to `/mnt/VMdata/Downloads/Incomplete` and moves the completed downloads to `/mnt/VMdata/Downloads/Complete/Category` where category is either sonarr or radarr. Sonarr and Radarr then pick the file up for import and should move to it's final location as `/mnt/media/library` where library is TVShows/Movies etc... Since that is the MergerFS mount and it writes local it's actually moving that data to `/mnt/VMdata/Downloads/TempMedia/library` however it's doing a copy+delete and can take upwards of 10+ minutes for a BluRay remux to import. 

I asked on trapexit's discord and he advised that since the move is `/mnt/VMdata/Downloads/Complete > /mnt/media/library` they are two different mounts. My assumption was that since mergerFS is actually causing the write to `/mnt/media/library` to be a write to `/mnt/VMdata/Downloads/TempMedia` that they would be considered the same but since the kernel doesn't see it that way, it sees two different mounts so it invokes a copy+delete. 

My thought was the MergerFS mount should be `/mnt/VMdata/Downloads:/mnt/m_crypt/ /mnt/media` So that Sonarr/Radarr/NZBGet can all just pick up downloads from `/mnt/media/Complete/Category` and then an atomic move should occur for it to go to `/mnt/media/library` but that would mean new downloads are going to be located at `/mnt/VMdata/Downloads/library` instead of `/mnt/VMdata/Downloads/TempMedia`. 

My daily move script is 

```
#!/bin/bash
# RClone Config file
RCLONE_CONFIG=/home/user/.config/rclone/rclone.conf
export RCLONE_CONFIG

#exit if running
if [[ "`pidof -x $(basename $0) -o %PPID`" ]]; then exit; fi

# Move older local files to the cloud
/usr/bin/rclone move /mnt/VMdata/Downloads/TempMedia/ m_crypt:/ --log-file /docker-data/scripts/mupload.log -v --delete-empty-src-dirs --max-transfer 700G
```
Which would need modified to just `/mntVMdata/Downloads m_crypt:/` except that directory is like a revolving door of data for me and there are a ton of other files there that aren't Shows/Movies and don't need to be presented to Plex at all or moved to the Google Drive. I don't think I can really use an excludes file there as I would constantly need to update it for any new files in `/mnt/VMdata/Downloads` which isn't really feasible. 

I also replicate all of the above for 4K instances of Sonarr/Radarr so `rclone mount 4k_crypt: /mnt/4k_crypt/ ` and `mergerfs /mnt/VMdata/Downloads/Temp4K:/mnt/4k_crypt/ /mnt/4kmedia`

I then manually run an upload script on that directory as 4K media is grabbed far less and often, and only after checking that the daily move of the regular media is done and that the total move size between them isn't going to exceed 700GB. I know the limit is 750GB but I play it safe. 

I guess I'm just having a hard time visualizing how to make this work without somehow pushing a bunch of data to the Google Drive that doesn't need to be moved, or accidentally deleting all the data on my Google Drive because I mistakenly move something to itself and `--delete-empty-src-dirs` 

Also trapexit recommended flagging the Gdrive mount as =RO or =NC since were not writing directly to the cloud drive. I'm guessing since Sonarr/Radarr need to be able to delete for upgrades that would be =NC. But I'm not sure how that would affect Sonarr/Radarr trying to move files by using the trick to rename Movie/Series folders. 

Sorry for the long winded issue here, just hoping you can provide some insight to help me visualize how to set this up. Thank you for any help you can provide.

**Comment by animosity22** [comment]
Your setup is way different than mine you are using SMB / dockers which over complicates things for me.

In my setup, I use one disk I call /local

Everything gets written to that one disk and hard links/everything works by writing there.

I use an exclude to stop my move from moving things I don't want there.

Best to test with just linking a file yourself so see if it works on the mergerfs mount point. If you can link it, great, if not, go back and troubleshoot your setup and see what path is not working right.

If you have a question on my setup, I can answer anything in particular.

**Comment by Dulanic** [comment]
All experience I had trying docker had 1 major issue. Timing. If mergerfs runs after docker, you'd have to reset the container. If rclone connection resets for any reason, you'd need to reset the container. Basically docker uses its own mounts. As much as I tried to get requires mount in systemd, it's a fickle bitch. I ended up adding a pre start sleep delay to get my docker timing to work.

**Comment by g4m3r7ag** [comment]
Thank you for the insight. I'm going to move my 4k media into the same crypt as regular media so I only need one mount and then move my temporary location into it's own folder so I can just do an exclude from and list my complete/incomplete/torrents directories. 

Any thoughts on trapexit's recommendation to flag the google drive as no-create? since we're not typically writing directly to the cloud drive through mergerfs?

**Comment by Dulanic** [comment]
I skip mergerfs and this is my rclone mount. Prob not perfect but I've used for over a year.

```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/dulanic/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount decrypt:Media /mnt/gd \
--allow-other \
--attr-timeout 60s \
--buffer-size 512M \
--dir-cache-time 240h \
--no-modtime \
--log-level INFO \
--vfs-cache-mode full \
--cache-tmp-upload-path /mnt/btrfs/rclone \
--cache-dir=/mnt/btrfs/rclone/cache \
--vfs-cache-max-size 100G \
--cache-tmp-wait-time 60m \
--poll-interval 15s \
--log-file /var/log/rclone.log \
--timeout 1h \
--umask 022 
ExecStop=/usr/bin/fusermount -uz /mnt/gd
Restart=on-failure
User=dulanic
Group=dulanic

[Install]
WantedBy=multi-user.target

```

**Comment by animosity22** [comment]
Closing this out as it's answerer / not really relevant for my setup.
