### ISSUE TITLE
Trash / Upgraded files

### ISSUE THREAD

**Issue by RaymondSchnyder** [animosity22/homescripts#62]
Hi!

Just wanted to ask you where you put your deleted / upgraded files?
As you mount rclone readwrite, are changes on files / in directories directly written onto the rclone mount?
Or do you upload those to?
What have you set as "trash folder" in radarr/sonarr? Do you just permanently delete them?
Doesnt that mean they stick in their original location on google drive?

**Comment by animosity22** [comment]
Everything is always written locally to my /local mount first per my mergerfs setup.

An upgrade is just deleted from the mergerfs mount (which may or may not be on the cloud part) and the new file is placed in the same spot.

Nightly, I upload any local files to my Google Drive.

I don't use a trash folder in Sonarr/Radarr as that's no value for me.

With mergerfs, the file path / location never changes as it's hidden beneath and mergerfs policy handles writing everything locally first.

**Comment by RaymondSchnyder** [comment]
> Everything is always written locally to my /local mount first per my mergerfs setup.
> 
> An upgrade is just deleted from the mergerfs mount (which may or may not be on the cloud part) and the new file is placed in the same spot.
> 
> Nightly, I upload any local files to my Google Drive.
> 
> I don't use a trash folder in Sonarr/Radarr as that's no value for me.
> 
> With mergerfs, the file path / location never changes as it's hidden beneath and mergerfs policy handles writing everything locally first.

Oh so if the file is already on the cloud, mergerfs deletes the file on the cloud with the rclone mount backend?

**Comment by animosity22** [comment]
Yep, which is why my rclone mount is read/write.

**Comment by animosity22** [comment]
Closing this out as it is answered.
