### ISSUE TITLE
upload_cloud takes ages before actually doing anything

### ISSUE THREAD

**Issue by jahknem** [animosity22/homescripts#63]
Hi! I'm using the configuration you kindly provided in almost exactly the same way. However due to limited storage (120 GB for everything) I instead have the upload_cloud script run every 15 minutes. This is to upload already finished downloads as soon as possible so to make room for more downloads. The script seems to take very long to scan before it uploads. Is there any way to make this faster? 
Getting more storage sadly is not an option.

Attached is the script in which I've only changed the user agent and removed --min-age

```
#!/bin/bash
set -e

# RClone Config file
RCLONE_CONFIG=/opt/rclone/rclone.conf; export RCLONE_CONFIG
RCLONE_USER_AGENT=TendenziellTendenzioeseAkten; export RCLONE_USER_AGENT

# Local Drive - This must be a local mount point on your server that is used for the source of files
# WARNING: If you make this your rclone Google Drive mount, it will create a move loop
# and DELETE YOUR FILES!
# Make sure to set this to the local path you are moving from!!
LOCAL=/local

# Exit if running
if [[ $(pidof -x "$(basename "$0")" -o %PPID) ]]; then
echo "Already running, exiting..."; exit 1; fi

# Check for excludes file
if [[ ! -f /opt/rclone/scripts/excludes ]]; then
echo "excludes file not found, aborting..."; exit 1; fi

# Is $LOCAL actually a local disk?
if /bin/findmnt $LOCAL -o FSTYPE -n | grep fuse; then
echo "FUSE file system found, exiting..."; exit 1; fi

# Move older local files to the cloud...
# I added in 3 days to let the files sit a few days so Plex intro anaylsis can happen locally
/usr/bin/rclone move $LOCAL gcrypt: --log-file /opt/rclone/logs/upload.log -v --exclude-from /opt/rclone/scripts/excludes --delete-empty-src-dirs --fast-list --drive-stop-on-upload-limit
```

**Comment by animosity22** [comment]
Words like slow / ages don't actually mean anything.

If you want to share some specifics on the timing and a log file, that would be helpful.

If I had to guess, I'd imagine you are running on a slow disk and are perhaps IO bound, but that's just a guess.

Are you uploading to an encrypted remote or a non encrypted remote?

**Comment by kennyparsons** [comment]
@animosity22 @jahknem It could be the `--fast-list` option. It's memory saving, but I also experience a delay in scanning and starting the actual move process.

**Comment by animosity22** [comment]
fast-list speeds things up at the cost of memory rather than making multiple API calls.

**Comment by animosity22** [comment]
A delay? 1 second? 1 minute? 1 hour? Need a log file or some details to help assist.

**Comment by jahknem** [comment]
Of course. Currently the uplaod script has been running for 1.5 hours without uploading anything. I'm running an a sata ssd and currently have very little IO delay of about 0-3%. I am running in a VM and have got 6 cores of an intel xeon which I believe is an X5650. The server is hosted in a datacenter and has a connection of 100 mbit up and down.
Attached you may find todays logs. (I had -vv in the script until yesterday afternoon, so the rest of the logs got quite large)
[upload2_log.txt](https://github.com/animosity22/homescripts/files/6399226/upload2_log.txt)

**Comment by jahknem** [comment]
> A delay? 1 second? 1 minute? 1 hour? Need a log file or some details to help assist.

Yes sorry. I did not expect you to reply this soon. Please tell me what further details you need.
I've currently got about 70 TB of data in the cloud, so this could probably impact the delay?

**Comment by animosity22** [comment]
There aren't any errors in that log file other than what looks like a slow upload speed. You are only getting 1.8MB/s.

**Comment by animosity22** [comment]
An example on a good connection:

Transferred:      454.264G / 454.264 GBytes, 100%, 87.258 MBytes/s, ETA 0s
Checks:               102 / 102, 100%
Deleted:               51 (files), 54 (dirs)
Renamed:               51
Transferred:           51 / 51, 100%
Elapsed time:   1h29m56.3s

**Comment by jahknem** [comment]
My speed is limited to 100 Mbit which is a combined limit for up and down. This means the upload speed is low If it is downloading at the same time or if I'm streaming of the server.  However the speed is not what I'm worried about. Rather it is the long time it takes until the uploads starts which is a problem.
You can see in line 1990 of the log how the script suddenly starts uploading with 4.5 Mbit but not registering the files before that.

**Comment by jahknem** [comment]
I've had this issue with a different server running on the same google drive, too. Attached are the logs. At about 40 minutes after the start it will begin moving files, not before. Could this be an issue with the very large amount of files on the google drive?

You mentioned that this could be an IO Issue. How so, is it because rclone needs to save a list of files on the disk or because it is analyzing the files on the disk before uploading them?

[upload3_log.txt](https://github.com/animosity22/homescripts/files/6400474/upload3_log.txt)

**Comment by animosity22** [comment]
You have duplicates and errors in the log.

```
021/04/29 02:32:22 NOTICE: music/Loverboy/Zróbmy Sobie Fotę [2015]: Duplicate directory found in destination - ignoring
2021/04/29 02:32:25 NOTICE: music/Leonard Bernstein/The Leonard Bernstein Collection - Volume 1 - Part 1 [2014]/CD12/19 - Gundula Janowitz - Fidelio op.72 - Act 1 - Beethoven- Fidelio, Op. 72 - Act 1 - -Nun sprecht, wie ..- - -Ach Vater, eilt- - -Verwegner- (Live At Musikverein, Vienna - 1978).flac: Duplicate object found in destination - ignoring
2021/04/29 02:32:26 ERROR : music/Heinz Rudolf Kunze/Kunze Macht Musik [1994]/09 - Heinz Rudolf Kunze - Du gehörst zu jemand andrem.flac: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-Uw_LCtxTFDnZGW4LmuqMtPaOguX2iwQJjh9y-MPXO-sWYSqJpTaMYdL4K4nqS6a6Qtb7OV5CRruhzA8Z7VWsUYNBrrW2A": read /storage/shared/music/Heinz Rudolf Kunze/Kunze Macht Musik [1994]/09 - Heinz Rudolf Kunze - Du gehörst zu jemand andrem.flac: input/output error
```

You want to clean up the errors and once that is done, run with -vv and share the debug log if there are still issues.

**Comment by jahknem** [comment]
Still working on cleaning my errors up. Makes no sense to keep this open if I'm not sure if it is a system error
