### ISSUE TITLE
plex permission problem

### ISSUE THREAD

**Issue by snickers2k** [animosity22/homescripts#67]
hey.
thank you for your scripts and explanations. really helped a lot.

but since using your scripts with mergerfs it's not possible anymore for me to delete files through plex. it worked using only GDrive.
seems a permission problem i can't find. i'm using 100% your scripts. so i wonder if you maybe have an idea.

plex is associated to group "main-group", aswell as mergerfs and gdrive is using that user "main-user" associated to "main-group" ... so can't really find the issue :(

thank you

**Comment by animosity22** [comment]
If you can't delete, it definitely sounds like a permission issue but not really enough info to help out.

You'd want to ls -al on the file and validate you have the right group permissions.

I use:

https://forums.plex.tv/t/customizing-your-plex-configuration/205443

and run Plex and mergerfs/etc all as the same user.

**Comment by animosity22** [comment]
Let me know if you have anything else as I hope you got it fixed!
