### ISSUE TITLE
SSD Caching + Scan

### ISSUE THREAD

**Issue by Tawagot0** [animosity22/homescripts#69]
Hello, I have an SSD like your configuration only dedicated for the Plex cache, however I would like to know how is mounted your disk for the cache, is it configured in LVM or it is just mounted in a folder like in your rclone.conf file?

```bash
# The local disk used for caching
--cache-dir=/cache \
```
I'm using LVM for the moment for speed (NVME with the OS installed on it + an SSD extension for the cache)
Because I noticed that a simple mount in a folder, when we try to do a transfer of the Plex config folder for testing (so between the main NVME to the SSD Cache) is very very slow. 
However the LVM is a very bad idea because if the SSD for the cache falls all my server falls.

Another question, could I have your scan settings for Plex please? (Plex Settings > Library)
Because I wonder how you do for Sonarr/Radarr upgrades if it generates a "Trash" icon for you, because if the option is checked when Plex empties the trash every time the mount crashes Plex will take care of deleting everything.
Thanks!

**Comment by animosity22** [comment]
My cache disk is just a standard SSD mounted as ext4.

```
felix@gemini:~$ mount | grep cache
/dev/sda1 on /cache type ext4 (rw,relatime)
```

I have a script that runs every so often to empty the trash as if the box is checked to empty after a scan and your mount isn't there, it'll delete your entire library so that's not something I want.

It's there now as well:

https://github.com/animosity22/homescripts/blob/master/scripts/plex-empty-trash

**Comment by Tawagot0** [comment]
Thanks for the script! I think it's a very good idea to make a check on more than 100 items, I think to modify your script to add a little more control (for example if mounted folder is not empty) if you are interested I can make a merge request.
Thanks again, you can close the issue or I can do it if you want.

**Comment by animosity22** [comment]
Sure by all means as if you have a way to improvement, I will definitely take it! So I can close this out and if you want to do a pull or ever just paste it into here. Whichever is easier for you.
