### ISSUE TITLE
Rclone.conf incomplete?

### ISSUE THREAD

**Issue by ashmodai6** [animosity22/homescripts#7]
Hi ! First thanks a lot for sharing your setup. I am trying to move away from Plex drive since I got quite some issues recently and i tried to get inspiration from your setup. I am confused by your rclone.comf since your gmedia mount refers a gcache one which is not present ? Are you still using cache ?

**Comment by animosity22** [comment]
Jus legacy as I keep that around for testing is folks have questions. I only use the vfs read chunk features at that performs better for me.

**Comment by sbcrumb** [comment]
What version of rclone are you using I can't get the vfs commands to work they claim to not be valid. I am using 1.43.1

**Comment by animosity22** [comment]
Sorry as I didn't see this.

I'm guessing you don't have a later version if the commands aren't working.

You can check via rclone version

If you had commands that aren't working properly, you can always hit the forums as well.
