### ISSUE TITLE
Failed to enable rclone.service (invalid argument)

### ISSUE THREAD

**Issue by wakhaiha** [animosity22/homescripts#70]
Hi. I am having a problem enabling rclone.service at my dedicated server (provided by OneProvider). I have installed rclone through swizzin. Previously, I have successfully enabled Rclone Mount using Systemd by following [this guide](https://docs.usbx.me/books/rclone/page/rclone-mount-using-systemd). However when I am trying to go advance by [setup Rclone vfs and MergerFS](https://docs.usbx.me/books/rclone/page/rclone-vfs-and-mergerfs-setup), I found that MergerFS folder only showing file from the local folder, not from Google drive folder. That is when I tried to find another guide and found this github. 

below is my server info:
```
wakhaiha@kadhs:/etc/systemd/system$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
I have configured rclone and  setup google drive remote as `gdwakg:`. my rclone config is at `/home/wakhaiha/.config/rclone/rclone.conf`. 
my folders & files  as below:
rclone mount point   : `/home/wakhaiha/Mount/gdwakg`
rclone log file            : `/home/wakhaiha/scripts/rc_cache/gdwakg.log`
cache-dir                   : `/home/wakhaiha/scripts/rc_cache/wakg`

below is log from command line and error message when enabling rclone.service.

```
wakhaiha@kadhs:/etc/systemd/system$ sudo nano rclone.service
wakhaiha@kadhs:/etc/systemd/system$ sudo systemctl daemon-reload
wakhaiha@kadhs:/etc/systemd/system$ sudo systemctl enable --now rclone.service
Failed to enable unit: File rclone.service: Invalid argument
wakhaiha@kadhs:/etc/systemd/system$ cat rclone.service
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/wakhaiha/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount gdwakg:Entertainment /home/wakhaiha/Mount/gdwakg \
# This is for allowing users other than the user running rclone access to the mount
--allow-other \
# Google Drive is a polling remote so this value can be set very high and any changes are detected via polling.
--dir-cache-time 5000h \
# Files are never changed for me outside of the mount so the attr-timeout matches the dir-cache
# Please make sure to read: https://rclone.org/commands/rclone_mount/#attribute-caching
# To understand if this should be set for your use case
--attr-timeout 5000h \
# Log file location
--log-file /home/wakhaiha/scripts/rc_cache/gdwakg.log \
# Set the log level
--log-level INFO \
# I reduce the poll internval down to 10 seconds as this makes changes appear fast the API quotas per day are huge
--poll-interval 10s \
# This is setting the file permission on the mount to user and group have the same access and other can read
--umask 002 \
# Please set this to your own value below
--user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36' \
# This sets up the remote control daemon so you can issue rc commands locally
--rc \
# This is the default port it runs on
--rc-addr :5572 \
# no-auth is used as no one else uses my server and it is not a shared seedbox
--rc-no-auth \
# The local disk used for caching
--cache-dir=/home/wakhaiha/scripts/rc_cache/wakg \
#
# If you are building a library from scratch and need to analyze a large amount of data, setting a very small read chunk size
# will make things download a lot less data. So you can uncomment this section out.
# If everything is already scanned, you can leave it at the default as it helps things startup a little faster.
#--vfs-read-chunk-size 1M \
#
# My quota per user / per 100 seconds is 10,000 requests. This can be found in your quota section.
# This changes the sleep calls to something much lower to take advantage of the API boost.
# change the min sleep from 100ms
--drive-pacer-min-sleep 10ms \
# Changing to have the ability for 1000 per second
--drive-pacer-burst 1000 \
# This is used for caching files to local disk for streaming
--vfs-cache-mode full \
# This limits the cache size to the value below
--vfs-cache-max-size 750G \
# This limits the age in the cache if the size is reached and it removes the oldest files first
--vfs-cache-max-age 5000h \
# The polling interval for increased based on there is enough buffer space
--vfs-cache-poll-interval 5m \
# Add read ahead buffer to network latency issues
--vfs-read-ahead 2G \
# This sets a per file bandwidth control and I limit this to a little bigger than my largest bitrate I'd want to play
#--bwlimit-file 32M
ExecStop=/bin/fusermount -uz /home/wakhaiha/Mount/gdwakg
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:5572 _async=true
Restart=on-failure
User=wakhaiha
Group=wakhaiha

[Install]
WantedBy=multi-user.target
{"mode":"full","isActive":false}
```

I have tried to remove multiple lines to see whether the problem is solved, but it didn't. Please let me know if my `rclone.service` not valid.

**Comment by maximuskowalski** [comment]
Where is your `rclone.service` file?
Try using
`sudo systemctl enable rclone.service`
It seems to have an invalid argument, maybe the `--now`, if it enables you can the start it with
`sudo systemctl start rclone.service`
And if that fails you can use status to check, 
`sudo sytemctl status rclone.service`
To see what point the failure is occurring or what it might be.

**Comment by wakhaiha** [comment]
@maximuskowalski 

> Where is your `rclone.service` file?

i parked it inside `/etc/systemd/system`.

below is the result from the suggested commands in the terminal:
```
wakhaiha@kadhs:/etc/systemd/system$ sudo systemctl enable rclone.service
Failed to enable unit: File rclone.service: Invalid argument
wakhaiha@kadhs:/etc/systemd/system$ sudo systemctl start rclone.service
Failed to start rclone.service: Unit rclone.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status rclone.service' for details.
wakhaiha@kadhs:/etc/systemd/system$ sudo systemctl status rclone.service
● rclone.service - RClone Service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Jul 23 13:35:26 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 13:35:27 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 13:37:08 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:33:41 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:34:03 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:34:38 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:34:52 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:35:11 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:35:21 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
Jul 23 15:35:30 kadhs systemd[1]: /etc/systemd/system/rclone.service:12: Missing '='.
wakhaiha@kadhs:/etc/systemd/system$
```
from the error message above, I had revisited rclone.service, line 12, but it seems line 12 is just a comment as shown below:
`# This is for allowing users other than the user running rclone access to the mount`
Or does the "12" in the error message above not represent line number?

attached is my rclone.service for reference. I converted it to txt file since github not allowed me to upload .service file extension.
[rclone.service.txt](https://github.com/animosity22/homescripts/files/6867239/rclone.service.txt)

**Comment by Tawagot0** [comment]
Line 12 is the whole command of rclone.
```
--vfs-read-ahead 2G \
#--bwlimit-file 32M
```

You need to remove the `\`  for the line `--vfs-read-ahead 2G \` because it is the last element of your order since you commented the option after.

**Comment by wakhaiha** [comment]
> Line 12 is the whole command of rclone.
> 
> ```
> --vfs-read-ahead 2G \
> #--bwlimit-file 32M
> ```
> 
> You need to remove the `\` for the line `--vfs-read-ahead 2G \` because it is the last element of your order since you commented the option after.

Oh, I see now. Thank you for helping me out. I removed `\` at line  `--vfs-read-ahead 2G \` but still failed to enable rclone service. Then I removed all the comment lines and put comment on the last line `#{"mode":"full","isActive":false}`. after that, it works. removing all comment lines & put comments on the last line alone does not work till you highlight my newbie mistake. thank you, sir!

on the other side, is there any effect if I put comment on last line : #{"mode":"full","isActive":false}` ?

**Comment by animosity22** [comment]
You'd have to post your full service file as you have a extra character somewhere.

**Comment by wakhaiha** [comment]
> You'd have to post your full service file as you have an extra character somewhere.

here is my rclone.service that works after @Tawagot0 commented. 
[Unit]
Description=Rclone Service wakg
Wants=network-online.target
After=network-online.target

```
[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/wakhaiha/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount gdwakg:Entertainment /home/wakhaiha/Mount/gdwakg \
--allow-other \
--dir-cache-time 5000h \
--attr-timeout 5000h \
--log-file /home/wakhaiha/scripts/rc_cache/gdwakg.log \
--log-level INFO \
--poll-interval 10s \
--umask 002 \
--user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36' \
--rc \
--rc-addr :5572 \
--rc-no-auth \
--cache-dir=/home/wakhaiha/scripts/rc_cache/wakg \
--drive-pacer-min-sleep 10ms \
--drive-pacer-burst 1000 \
--vfs-cache-mode full \
--vfs-cache-max-size 750G \
--vfs-cache-max-age 5000h \
--vfs-cache-poll-interval 5m \
--vfs-read-ahead 2G \
--bwlimit-file 32M
ExecStop=/bin/fusermount -uz /home/wakhaiha/Mount/gdwakg
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:5572 _async=true
Restart=on-failure
User=wakhaiha
Group=wakhaiha

[Install]
WantedBy=multi-user.target
#{"mode":"full","isActive":false}
``` 

I need to turn off {"mode":"full","isActive":false} in the last line to be able to enable the service. I guess maybe because I am running outdated systemd v242 for ubuntu 18.04.

I will close this issue now since it already solved. thank you all.
