### ISSUE TITLE
Rclone service shows to be failed but the commands are still executed

### ISSUE THREAD

**Issue by Horuyuki** [animosity22/homescripts#71]
Hello dev! Thanks for sharing your rclone config.

So since I plan on mounting more than one drive, I instead gave the `ExecStart` a bash script location. Same for the stop corresponding unmounting script.

They look something like this:
```
#!/bin/bash

/usr/bin/rclone mount tube-tear-seed: /home/tomato/rclone/tear-seed/ --allow-other --dir-cache-time 5000h --log-file /home/tomato/rclone/log/rclone.log --log-level INFO --poll-interval 5s --umask 002 --cache-dir=/home/tomato/rclone/cache --vfs-read-chunk-size 1M --vfs-cache-mode writes --vfs-cache-max-size 20G --vfs-cache-max-age 2h --vfs-cache-poll-interval 5m --vfs-read-ahead 2G 

#--rc --rc-addr :5572 --rc-no-auths
```

And the stop script is just your line with the mounting location changed.

And the systemctl status returned loaded, exited with status one. Still tho, contents inside the mounted dir and `ps x | grep rclone` shows me that the commands are running alright. I omitted the rc since I literally couldn't start it at all with that.

So my question is, is there a way to make it to be active? I want my torrent systemd to use `Require` this module.

**Comment by animosity22** [comment]
Not sure how I can help out as that looks like something you made yourself.

I wouldn't use a bash script in a service file.

You should have a service file per mount to keep things clean imo. 

You'll know your use case and setup better than me as I have my stuff setup for my use case.

Without seeing your full service file and the error, it's hard to tell.

**Comment by Horuyuki** [comment]
So after some modification here it is:
```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/tomato/.config/rclone/rclone.conf
KillMode=none
RestartSec=5

ExecStart=/usr/bin/rclone mount tube-tear-seed: /home/tomato/rclone/tear-seed/ --allow-other --dir-cache-time 5000h --log-file /home/tomato/rclone/log/rclone.log --log-level INFO --poll-interval 5s --umask 002 --cache-dir=/home/tomato/rclone/cache 
--vfs-read-chunk-size 1M --vfs-cache-mode writes --vfs-cache-max-size 20G --vfs-cache-max-age 2h --vfs-cache-poll-interval 5m --vfs-read-ahead 2G --rc --rc-addr :5572 --rc-no-auth --daemon

KillSignal=SIGKILL
ExecStop=/bin/fusermount -uz /home/tomato/rclone/tear-seed

#ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true 

#--rc-addr 127.0.0.1:5572 _async=true

Restart=on-failure

User=user
Group=user

[Install]
WantedBy=multi-user.target
```

I added the `SIGKILL` since before when stopping it, the service did not rid of the previous already running rclone command so it would always fail.
Commented out the `--rd-addr` because it seemed to actually fail with that option attached. Would you mind to briefly explain what  `vfs/refresh` does? Did some reading but I still wasn't sure of its purpose.

And I did adopt your suggestion of one service per mount. Looks like I will be creating rclone1.service and so on very soon.

**Comment by animosity22** [comment]
You are going on your on path now.

I don't use SIGKILL as that leaves orphaned things and a possible mount point issue.

refresh just loads the directory and file structure in memory so it's faster to browse the mount once it's mounted.

I'm going to close this out as this really doesn't have much to do with my settings anymore.
