### ISSUE TITLE
Wireguard 

### ISSUE THREAD

**Issue by jcastilloalonso** [animosity22/homescripts#79]
Hi,

I was reviewing your Wireguard code and trying to implement the same in my server. So far, I got wireguard up and running but can't make it run as a separate IP to just bind services to it as required.

Checking https://github.com/animosity22/homescripts/blob/master/WIREGUARD.MD

Basically the Table=Off and the PostUp and PostDown (to undo the PostUp change) are the only real changes you do.

Could you please expand the usual IP address of your server? Any further reading you recommend to check out on how to make it run? My server IP is on a different subnet so changes do not apply directly:

$ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.86.23  netmask 255.255.255.0  broadcast 192.168.86.255
        inet6 fe80::f3c3:670b:bbb:6cbc  prefixlen 64  scopeid 0x20<link>
        ether 48:ba:4e:b5:e6:f2  txqueuelen 1000  (Ethernet)
        RX packets 1098775591  bytes 1389257346636 (1.2 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 710804289  bytes 803479740833 (748.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 125  base 0xc000

So any help on how to make this work would be greatly appreciated as the service I want to add requires an IP from another country but don't want to route all my traffic through the VPN as it would slow a lot of services down.

Thanks a lot for your help!

Jose

**Comment by animosity22** [comment]
Closing out as this looks to be answered.
