### ISSUE TITLE
systemd[1]: Condition check resulted in gmedia mergerfs mount being skipped.

### ISSUE THREAD

**Issue by jcconnell** [animosity22/homescripts#82]
Curious if you've seen this before and if you may be aware of a resolution:

```
user@apps:/gmedia# systemctl status gmedia.service
● gmedia.service - gmedia mergerfs mount
     Loaded: loaded (/etc/systemd/system/gmedia.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Mon 2021-11-29 12:17:23 HST; 3s ago
             └─ ConditionPathIsMountPoint=/local was not met

Nov 29 11:39:48 apps systemd[1]: Condition check resulted in gmedia mergerfs mount being skipped.
Nov 29 11:49:43 apps systemd[1]: Condition check resulted in gmedia mergerfs mount being skipped.
Nov 29 11:55:19 apps systemd[1]: Condition check resulted in gmedia mergerfs mount being skipped.
Nov 29 12:17:23 apps systemd[1]: Condition check resulted in gmedia mergerfs mount being skipped.
```

My `gmedia.service` file is identical to your `media.service` file, though the paths have been updated. `/local` exists and is a mount point but the directory is not empty.

**Comment by animosity22** [comment]
Can you share your service file?

If you check /proc/mounts, does it show up?

```
root@gemini:/etc/systemd/system# cat /proc/mounts | grep local
/dev/sdb1 /local xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
local:DB:GD /media fuse.mergerfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```

Should see some output like that.

Did you systemctl daemon-reload after making any changes to the file?

**Comment by jcconnell** [comment]
Thanks for a quick reply!

```
user@apps:/local# cat /etc/systemd/system/gmedia.service
[Unit]
Description=gmedia mergerfs mount
ConditionPathIsMountPoint=/local
Requires=rclone.service
After=rclone.service

[Service]
Type=forking
ExecStart=/usr/bin/mergerfs /local:/gd /gmedia -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```
user@apps:/local# cat /proc/mounts | grep local
local:gd /gmedia fuse.mergerfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
```


I did do a daemon-reload after making changes. This started happening on reboots without making any changes to the unit file though. I have neglected determining the cause of the problem for a bit because I usually login and run `/usr/bin/mergerfs /local:/gd /gmedia -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true` to get working again in a pinch (until the next reboot).

**Comment by animosity22** [comment]
You seem to be missing a /local mount point, is it a mount or a directory on an already existing mount point?

This would confirm:

```
felix@gemini:~$ mountpoint /local
/local is a mountpoint
felix@gemini:~$ mount /rclonevfs
mount: /rclonevfs: can't find in /etc/fstab.
```

If it isn't a mount, you can change that line to ConditionPathIsDirectory.

My goal for that line was to make sure my local "caching" disk is mounted and if it is not mounted, do not start up mergerfs. YMMV if that is important for you or no, but that is why I added it.

I have a few checks so I don't get my Plex stuff fubared.

**Comment by jcconnell** [comment]
Ah, I see. It's a directory on an already existing mount point. 

```
user@apps:/local# mountpoint /local
/local is not a mountpoint
```

Changing to `ConditionPathIsDirectory` fixed it. Thank you for your help!
