### ISSUE TITLE
Question: Google Drive -> Dropbox conversion

### ISSUE THREAD

**Issue by needo37** [animosity22/homescripts#83]
Hello! I was wondering what process you followed to migrate all of your files you had within Google Drive to Dropbox. Thank you!

**Comment by animosity22** [comment]
I didn't do anything overly complex as I just:

1) Grabbed a cheap unlimited seedbox from Black Hosting
2) Chnaged my mergerfs mount to have my new dropbox mount before my drive mount
3) Ran a rclone move GD: DB:

Let that run for about 2-3 weeks and everything was done. I also changed any new stuff to upload to my DB rather than GD. I would get anywhere from 3-5TB per day moved so I just had to wait it out.

**Comment by needo37** [comment]
Thank you!

I assume you used different service accounts on GD to get around the 750GB/day limit.

**Comment by animosity22** [comment]
That's upload per day. This is download so I didn't hit any issues with that as I only did 3-5TB per day.

**Comment by needo37** [comment]
Gotcha! One last question if you don't mind. How much is Dropbox costing you a month? They quoted me $60/month.

**Comment by animosity22** [comment]
So I've seen posts floating around with people wanting to split costs as it's $20 per user with a minimum of 3. I'm a hermit and don't mind paying a little extra for only me to be sure.

I don't hit any download/uploads limits and the API rate limiting is not bad at all for me as I've had no issues as they don't publish their exactly rate limits but via rclone issues, I think my setup is fine and you can use additional apps to separate your workload as it's per app, not per user.

All that made it much more attractive to me. I'm not trying to convince anyone else to change or do anything else. Do what works for you and if residing in Google's limit and only paying $20 per month for 1 user, go for it. 

I've always tried to say, use what's best for your situation as my use case and perspective is perfect for me but might not be for you.

**Comment by needo37** [comment]
Thank you!

**Comment by bad1dea** [comment]
@animosity22 hey mate.. quick question.. do you have to request additional storage? I'm about ready to pull the trigger, but I have a lot of data, and I'm not sure I'm going to get away with asking for ... the amount of TB.

**Comment by animosity22** [comment]
So as I had the same concern, I signed up, requested the amount of storage for my migration that I needed.

They did have to escalate that to next level and I got my seed storage in about 30 minutes total.

Every month or so now, I ask for X more and I guess it depends on how you grow as I got 20TB at a time these day as for me, that's give me a few months without much issue.

I've heard folks that have a PB or two sitting there but I'm the only person on my setup and I'm not anywhere near a PB.

**Comment by animosity22** [comment]
I'd just trial, ask for what you need and go from there. I did roughly a 200TB migration.

**Comment by bad1dea** [comment]
Appreciate your response sir!

Thanks

**Comment by WoisWoi** [comment]
> app

Hey :)
What do you mean by "app" ? app = remote on rclone ?
Or is it (my I guess) this : https://www.dropbox.com/developers/apps/create ?
Is it fine with a full Dropbox access ?

Thanks you

**Comment by animosity22** [comment]
See:

https://rclone.org/dropbox/#get-your-own-dropbox-app-id

**Comment by WoisWoi** [comment]
> See:
> 
> https://rclone.org/dropbox/#get-your-own-dropbox-app-id

Thanks, I get this error when trying to mount my team folder. I guess I did something wrong :(

**Comment by animosity22** [comment]
For rclone support, I'd suggest using the rclone forums.
