### ISSUE TITLE
Access Denied for Thumbnails etc.

### ISSUE THREAD

**Issue by LubricantJam** [animosity22/homescripts#84]
Hey!

Loving the scripts, they've helped me out a bunch. Unfortunately, it seems all my metadata and cache has to be stored in my config locations due to it not having correct permissions due to the `/media` being a mount of both the `local` folder and the `DB_Content` folder. 

Obviously if you make a file inside the rclone mount directory, it goes across fine to Dropbox so I don't see the issue at all. Do you have any insight as to what is occurring?

```[2021-12-27 13:20:51.472 -05:00] [ERR] [34] MediaBrowser.Providers.Manager.ProviderManager: UnauthorizedAccessException - Access to path "/media/tv/The Blacklist (2013)/folder.jpg" is denied. Will retry saving to "/config/data/metadata/library/a5/a57c6d60cc28625ac07a6b883d7ad0aa/poster.jpg"```

Above is one of the errors I will get.

**Comment by animosity22** [comment]
I run my mount and Plex as the same user to avoid and permission issues. Are you running them as the same user or different?

If different, you may need to adjust the umask to make sure items and directories are created right.

**Comment by LubricantJam** [comment]
> I run my mount and Plex as the same user to avoid and permission issues. Are you running them as the same user or different?
> 
> If different, you may need to adjust the umask to make sure items and directories are created right.

I’m running Jellyfin rather than Plex but yeah they’re the same users. Just seems odd how everything is fine bar the merge.

**Comment by animosity22** [comment]
Can you share your output?

```
felix@gemini:~$ id
uid=1000(felix) gid=1000(felix) groups=1000(felix),4(adm),24(cdrom),27(sudo),30(dip),44(video),46(plugdev),109(render),116(lxd)
felix@gemini:~$ ls -al / |grep media
drwxrwxr-x   1 felix felix          0 Dec 29 09:06 media
```

/media is my merger mount.

**Comment by animosity22** [comment]
Closing out and let me know if you have any other questions.
