### ISSUE TITLE
Dropbox Queries

### ISSUE THREAD

**Issue by joe2707** [animosity22/homescripts#88]
Hi Animosity,

Sorry to bother you, I am also looking to use DropBox instead of Gdrive and just had a few queries on your config.

I have taken note that you mentioned having a different API app for uploads, movies & TV.

I see that in your Rclone config you only have a single config for Dropbox where you have specified a client / secret for one of these apps, but how are you then pointing rclone to the other API app clients / secrets for each individual part ? I can't seem to fathom that part out, how you're actually splitting these.

I hope this question makes sense !

Thanks in advance.

**Comment by animosity22** [comment]
I could probably make a better sample rclone.conf

I have a remote for each.

So like DBTV: DBMovies: and each remote is configured with a specific client ID/secret.

It's a bit of overkill as with the proper limits I don't generally see issues, but for some redundancy if my one mount has an issue, it doesn't impact the other.

**Comment by animosity22** [comment]
I updated my sample rclone.conf as well.

Let me know if you have any other questions.

**Comment by joe2707** [comment]
Thanks for this, I did manage to figure it out in the end as how you explained it helped a lot :)

I have found that streaming from dropbox stutters a lot though, and that's on a 10Gbit server, never had anything like that in the time I was using GDrive.

Have you noticed anything similar since using dropbox ? I have used the recommended configs for mounts etc that you have provided, so just seems strange.

Thanks

**Comment by animosity22** [comment]
Not at all. My server and players are all in my house though so I rarely have any issues since cache mode full would take care of any small blip in internet latency.

Both GD and DB have no issues maxing out my home gigabit.

**Comment by joe2707** [comment]
Strange, I am also using cache mode full.

ah well was worth a try, thanks again for your help and for the great guides ! they are a massive help.

**Comment by animosity22** [comment]
If you check the logs, full tends to avoid any internet blips.

If server and player are in the same spot, stuttering would be more something like a plex server over burdened or something along those lines.

If player / server are in different spots, that tends to be internet peering and not a thing you can really do.
