### ISSUE TITLE
should vfs-cache-mode be set to minimal or writes or full?

### ISSUE THREAD

**Issue by jetskijoe** [animosity22/homescripts#9]
Do the vfs flags even apply if you do not turn on vfs-cache-mode?  I don't see anywhere that the vfs-cache-mode is enabled.  

  --vfs-cache-mode string Cache mode off|minimal|writes|full (default "off")

**Comment by animosity22** [comment]
I don't use vfs-cache-mode as it's off by default.

The vfs backend is the default backend so it's used and the chunk read options are already merged in and pretty much the defaults I have set for the most part.

**Comment by animosity22** [comment]
Let me know if you get any other questions. You can always post on the forums as well.
