### ISSUE TITLE
Rclone Union

### ISSUE THREAD

**Issue by mouzzampk2014** [animosity22/homescripts#90]
Hi, I'm following your changelog and thanks for all the work. I'm still using google but your setup is simple and work. 

I can see you moved from mergerfs to rclone union but that means your hardlinks are not working? I'm still using mergerfs but I thought I should check with you before I move to union too :)

Also I couldn't find how are you running upload_media and how you mounting your rclone union. Would be great if you can direct me to right place to find the example. 

Also you mentioned you are moving toward docker so that means you are using rclone and all other services in docker? If that's the case could you please share your compose. I have all services running in docker too including mergerfs and rclone. 

Thank you 

Edit: I was typing last night so didn't know what I was asking so I tidy up little bit :)

**Comment by animosity22** [comment]
Correct - I don't use hardlinks anymore as you can't with just rclone mounts as it's not supported.

I don't use an upload script as it's all done on the mount.
I don't use union either as I note on my path. I have a mount for Movies and a mount for TV.

Uploads are handled by each mount themselves.

I don't use docker for rclone as for a few small binaries, I don't feel the need.

General flow is that Radarr/Sonarr get a file and drop it on a local storage. Radarr/Sonarr copy to the rclone mount. The rclone mount has a flag to delay uploads (I use 1 hour). Rclone uploads from the mount.

**Comment by animosity22** [comment]
I've also been working on updating the readme to be a bit more verbose. Not sure if that helps or not as I just didn't have much time until recently.

**Comment by shawnp0wers** [comment]
Only tangentially related, but I wanted to add that your updates are *incredibly* appreciated. I'm a mostly silent observer, but refer back to your work here regularly. And while my setup isn't identical, you've saved me countless hours and unimaginable frustration by sharing what works and what you do, even when it drastically changes over time.

So like, thanks and stuff. :)

**Comment by mouzzampk2014** [comment]
Hi @animosity22 you made it so easier and no extra mergerfs or scripts are involved and simple rclone doing its stuff. Awesome and great work :) 

Can I ask something not relevant to guides as you have sucha great experience in rclone so I thought I should ask. 
My hardware is very similar to yours and plex is on SSD instead of nvme.  I'm getting lot of 200ms sqlite3 errors. If you have any idea how can I prevent these. 5his happens during scans and only for tv shows or maybe with movies too but I never seen. 

Thanks

**Comment by animosity22** [comment]
Those are generally harmless and not much you can do. Plex expects files to be disk based and when it takes longer for them to come from a cloud remote, you tend to get those. 

You can also get those if you have the plex DB on a slow disk, but doesn't sound like that's the case. An optimize may help if something is off, but I generally never care about those and let my normal schedule optimize the database weekly as it's just cloud remote latency and nothing you can do about it.

**Comment by mouzzampk2014** [comment]
Thank you so much for the clarification and thanks again for the updated README. I can close this request.

Thanks
