### ISSUE TITLE
Clarification about Data and Cache

### ISSUE THREAD

**Issue by mouzzampk2014** [animosity22/homescripts#92]
Hi @animosity22 its me again 🙂 

Thanks for the tips you provided preciously I have up and running everything. 

Can I check with you one thing, you have data for local storage, media for cloud storage and cache for rclone. 

If the media is downloading onto data and then move to media that means radarr move the files from data to media via cache. If I'm correct then files are copying from one drive (data) to cache (rclone) before upload to media. Isn't this affecting the drives instead of just downloading directly on the cache. 

I hope I'm making sense :)

Thanks 😊

**Comment by animosity22** [comment]
Did you see my workflow?

https://github.com/animosity22/homescripts#my-workflow

You can't copy directly to the cache, you copy to a mount location which does it's own thing and uses the cache.

**Comment by mouzzampk2014** [comment]
Thanks for getting back to me. 
My workflow is basically is same as yours. I have SSD where nzbget downloading the files and then radarr move the files to gdrive then I have rclone cache set to external drive 20TB Raid 0. 

I think I'm just overconplixating the stuff. I was thinking to download the files into external drive then move files to gdrive that way cache and downloading will be on the same drive but only issue is nzbget struggles with hdd as compare to ssd.

**Comment by animosity22** [comment]
Really up to you. I use spinning disk as noted in my flow so it really doesn't matter if it takes 30 seconds or 3 seconds.
