### ISSUE TITLE
Intro script

### ISSUE THREAD

**Issue by edrock200** [animosity22/homescripts#93]
Does your intro script trigger intro detection for missing?

Would you happen to know which tables/fields to export/import across to Plex servers that share the same source library to migrate intro data?

**Comment by animosity22** [comment]
Sorry as I'm not following the question.

What you do you mean for missing?

Not sure on the second question either. Plex forums would be a great place as they would definitely know more than me.

**Comment by edrock200** [comment]
Ahh ok thanks. Was trying to use your script to determine where the intro data is stored in the db and was trying to see what your script does specifically, if it triggers intro scanning for shows that were missing intro data. Thanks for the reply.

**Comment by animosity22** [comment]
Someone helped and did a PR for it so unfortunately I'm not familiar enough myself. Sorry.

**Comment by animosity22** [comment]
Closing out as I unfortunately can't help.
