### ISSUE TITLE
Question re: migrating away from upload_cloud script

### ISSUE THREAD

**Issue by seannymurrs** [animosity22/homescripts#94]
I hope it's ok that I'm asking this question here, and I apologize in advance if it isn't. I set up my workflow a few years back, and it is very heavily based on your setup at the time. My Plex server is installed on a seedbox (Whatbox). My media is stored on my Google Drive, and it is mounted to my box via rclone. I'm using mergerfs and your old upload_cloud script to automate the movement of files from my box's local storage over to my gdrive account. I saw recently that you no longer use mergerfs or the upload_cloud script and instead rely on rclone's VFS cache to handle the process of moving files over to cloud storage (or at least that's what I believe you're doing). I'd like to do the same with my setup, and I was hoping you could help me ensure I configure things correctly. Below is my current rclone mount and mergerfs settings. Other than adding the `--vfs-write-back 1h` flag, is there anything else I need/should change to make things work? For my current settings, I used your setup as a starting point, and tried to figure out what (if anything) I needed to adjust for my needs. Unfortunately, I'm still pretty new to all of this, so I can't honestly say I fully understand what all the various flags/settings do. If helping me out with this is more work than I initially thought, please feel free to tell me so and I can look elsewhere for answers. Thanks!

```
#rclone
rclone mount \
--log-file ~/logs/rclone.log \
--log-level INFO \
--dir-cache-time 5000h \
--poll-interval 10s \
--attr-timeout 5000h \
--cache-dir=cache \
--vfs-cache-mode full \
--vfs-cache-max-size 200G \
--vfs-cache-max-age 5000h \
--vfs-cache-poll-interval 5m \
--vfs-read-ahead 2G \
--bwlimit-file 200M \
gdrive: /home/seannymurrs/gdrive \
--daemon \
&&

#mergerfs
mergerfs -o rw,use_ino,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full,dropcacheonclose=true /home/seannymurrs/files:/home/seannymurrs/gdrive /home/seannymurrs/gmedia
```

**Comment by animosity22** [comment]
I don't use mergerfs in my setup at all.

So the write-back is just saying that it stays in the local cache for an hour before it uploads.

**Comment by animosity22** [comment]
Closing as answered and nothing else popped in.
