### ISSUE TITLE
[QUESTION] Multiple dropbox mount in a mergerfs and Plex library scan

### ISSUE THREAD

**Issue by WoisWoi** [animosity22/homescripts#95]
Hi,

(context in the title) Do you know if Plex is capable to detect the changes in order to automatically scan the files concerned ?
(since I did not manage to make this work from my tests)

Thanks you :)

**Comment by animosity22** [comment]
I don't believe it works as rclone doesn't support inotify so Plex doens't know a change happens.

I have everything local.

Check out:

https://github.com/l3uddz/plex_autoscan

As that has a few things that may work.

If not, I'd just let Plex scan as much as it needs and set it to every 15 minutes or something if you can't use the Sonarr/Radarr integration.

**Comment by WoisWoi** [comment]
I'm already using plex_autoscan, but it's not working as intended.
I'd like my content to be scanned ASAP, but in the other hand, everything has to be scanned. Problem is, sometimes it'll scan a show, but only a few episodes will be detected (cause it's still uploading).

**Comment by animosity22** [comment]
Not sure what else to say as that's not something I use or run into as that's not my setup. 

If you have any questions related to my scripts or my setup, I'm happy to help.
