### ISSUE TITLE
Why rclone mount in docker override?

### ISSUE THREAD

**Issue by dannymichel** [animosity22/homescripts#97]
Wouldn't you want docker not to start until mergerfs is loaded because you're running things from mergerfs rather than rclone?

**Comment by animosity22** [comment]
I don't use mergerfs but that would make sense to me.

**Comment by dannymichel** [comment]
Why do you still have https://github.com/animosity22/homescripts/blob/master/systemd/media.service here?
You know longer have sonarr/radarr etc. set up for mergerfs? You just upload to dropbox on a schedule and run everything via rclone?

**Comment by animosity22** [comment]
It's documented in my workflow:

[![image](https://user-images.githubusercontent.com/5088712/191973902-821cdfa1-c5a6-47ae-8f9c-31bb853b62e9.png)
](https://github.com/animosity22/homescripts#my-workflow)

I left old scripts because folks asked me to as I wanted to remove them but some folks wanted a resource to see what a mergerfs looks like or a google drive mount.

**Comment by dannymichel** [comment]
Ok i see

**Comment by dannymichel** [comment]
> It's documented in my workflow:
> 
> 
> 
> https://github.com/animosity22/homescripts#my-workflow
> 
> 
> 
> I left old scripts because folks asked me to as I wanted to remove them but some folks wanted a resource to see what a mergerfs looks like or a google drive mount.

I'm the workflow it says things are copied from data to your rclone drive but how? On a schedule you've made a cron for or from sonarr itself when it tries to hard-link copies instead?

**Comment by dannymichel** [comment]
> Through a normal copy command as the mount can accept writes. You can't hard link to a rclone mount.
> 
> 
> 
> #4 step in that work indicates it waits for the delay I have to upload which in my case is 1 hour.

You do this copy command or sonarr does? Because i guess where I'm confused is that I only see move and hardlink options in sonarr

**Comment by animosity22** [comment]
Sonarr/Radarr all do that.

![image](https://user-images.githubusercontent.com/5088712/192013020-1982e926-390f-43e4-a750-a68348dc3e33.png)

**Comment by dannymichel** [comment]
> Sonarr/Radarr all do that.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5088712/192013020-1982e926-390f-43e4-a750-a68348dc3e33.png)
> 
> 

Wow I feel stupid

**Comment by dannymichel** [comment]
Was the final decision to stop using mergerfs due to speed or something broken or was it purely to avoid having to rely on it?

**Comment by animosity22** [comment]
Just removing components that I didn't feel were needed.

I rather have less software if possible and the trade off of an extra hour of double storage was fine for my use case.

So instead of managing an upload script, the mounts do that already and less things to monitor and break.

**Comment by dannymichel** [comment]
i see
