### ISSUE TITLE
Dropbox speeds

### ISSUE THREAD

**Issue by RemuxKid** [animosity22/homescripts#98]
Big fan of your workflow. I just had a quick question related to Dropbox.

From what I can see, it looks as if Dropbox doesn't push/pull as well as your former storage provider, Google.

Example you'd posted:
> felix@gemini:/data$ rclone copy jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv DB: -P
Transferred:   	    1.402 GiB / 1.402 GiB, 100%, 25.155 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        53.7s
felix@gemini:/data$
felix@gemini:/data$
felix@gemini:/data$
felix@gemini:/data$ ls
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv  local  rsnapshot  seed  t  test
felix@gemini:/data$ rclone copyto DB:jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv test.mkv -P
Transferred:   	    1.402 GiB / 1.402 GiB, 100%, 65.082 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        22.1s

The download speeds do not seem too bad, but how does it perform for you on your mount?

When I tested it with your mount script, it ranges between 8-25 MB/s. This was tested on Linux with the pv command to show copy progress. No values have been amended from your config. I'm curious to know if you deem this as 'acceptable' based on the way mounts work, or if it's me and bad peering.

By contrast, Google does max a gbit line (107 MB/s)

**Comment by animosity22** [comment]
I see much better speeds when I copy from Dropbox. Download is generally the same as Google's API, but I could always single upload much faster.

```
rclone copyto DB:jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv /tmp/blah.mkv -P
Transferred:   	    1.402 GiB / 1.402 GiB, 100%, 69.409 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        21.1s
```

I've never had any issues streaming any content on Google or Dropbox.

**Comment by RemuxKid** [comment]
So that's matching my speeds too. When using the copy command without the mount, I'm getting around 70 MB/s. Which looks good.

What I'm specifically referring to is the mount. 

**No mount:**

`rclone copyto db-secret:jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv . -P
Transferred:        1.402 GiB / 1.402 GiB, 100%, 62.932 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        23.6s`

**Mount:**
Avg speed 18 MB/s
`rsync -P jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv /tmp-NXpY/
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
  1,504,953,150 100%   19.58MB/s    0:01:13 (xfr#1, to-chk=0/1)`

**Comment by animosity22** [comment]
Mount speeds are the same for me.

Not sure what mount you are running/version/any other details / debug log / cache disk speed.

**Comment by RemuxKid** [comment]
Here's my service file

`[Unit]
Description=RClone Service Dropbox
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/opt/rclone/rclone.conf
RestartSec=5
ExecStart=/usr/bin/rclone mount db-secret: /mnt/Dropbox \
# This is for allowing users other than the user running rclone access to the mount
--allow-other \
--read-only \
# Dropbox is a polling remote so this value can be set very high and any changes are detected via polling.
--dir-cache-time 9999h \
# Log file location
--log-file /opt/rclone/logs/dropbox-mount.log \
# Set the log level
--log-level DEBUG \
# This is setting the file permission on the mount to user and group have the same access and other can read
--umask 002 \
# This sets up the remote control daemon so you can issue rc commands locally
--rc \
# This is the default port it runs on
--rc-addr 127.0.0.1:5580 \
# no-auth is used as no one else uses my server and it is not a shared seedbox
--rc-no-auth \
# The local disk used for caching
--cache-dir=/cache/DB-TEST \
# This is used for caching files to local disk for streaming
--vfs-cache-mode full \
# This limits the cache size to the value below
--vfs-cache-max-size 800G \
# This limits the age in the cache if the size is reached and it removes the oldest files first
--vfs-cache-max-age 9999h \
# Set the tpslimit
--tpslimit 12 \
# Set the tpslimit-burst
--tpslimit-burst 12 \
# Disable HTTP2
--disable-http2
ExecStop=/bin/fusermount -uz /mnt/Dropbox
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:5580 _async=true
Restart=on-failure
User=root
Group=root

[Install]
WantedBy=multi-user.target`

DEBUG Log:
`2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504051200
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504051200 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=131072, offset=1504313344
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=131072, offset=1504182272
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504313344
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504313344 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504182272
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504182272 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=131072, offset=1504575488
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=131072, offset=1504444416
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504575488
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504575488 Size:131072} in [{Pos:0 Size:1504702464}] - present false
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504444416
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504444416 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=131072, offset=1504706560
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=131072, off=1504706560
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504706560 Size:131072} in [{Pos:0 Size:1504702464}] - present false
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=131072, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Read: len=118784, offset=1504837632
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): _readAt: size=118784, off=1504837632
2022/09/29 15:20:43 DEBUG : vfs cache: looking for range={Pos:1504837632 Size:115518} in [{Pos:0 Size:1504953150}] - present true
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >_readAt: n=115518, err=EOF
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=115518, err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Flush:
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): RWFileHandle.Flush
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Flush: err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Release:
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): RWFileHandle.Release
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): close:
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: setting modification time to 2022-09-29 13:01:19 +0000 UTC
2022/09/29 15:20:43 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc001be1240): >close: err=<nil>
2022/09/29 15:20:43 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Release: err=<nil>`

Let me know if you're needing more. There's thousands of lines, but this is the snippet at the end.

rclone version
`rclone v1.59.0
- os/version: debian 11.3 (64 bit)
- os/kernel: 5.18.0-9.1-liquorix-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.3
- go/linking: static
- go/tags: none`
Though has been tested with newer versions + beta

As for cache disk speed, advise me on how to test this please.

**Comment by animosity22** [comment]
Can you share the full debug log from the test?

What type of disk in /cache? SSD / Spinning disk?

**Comment by RemuxKid** [comment]
Ah, it's a HDD 7200RPM

As it's a load of lines, it's uploaded here:
https://mega.nz/file/E9gg3aDK#HOTmXoGij0GJpe_H6dAeljwyQWXMjlxuUJoJC99CgRg

**Comment by animosity22** [comment]
Possibly a slow disk?

Most of that log shows the files coming from cache and never even reading from dropbox.

If you check for present true / false, you can see if it's being served from disk or not.

```
2022/09/29 15:28:11 DEBUG : vfs cache: looking for range={Pos:1504313344 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:28:11 DEBUG : vfs cache: looking for range={Pos:1504444416 Size:131072} in [{Pos:0 Size:1504702464}] - present true
2022/09/29 15:28:11 DEBUG : vfs cache: looking for range={Pos:1504575488 Size:131072} in [{Pos:0 Size:1504702464}] - present false
2022/09/29 15:28:11 DEBUG : vfs cache: looking for range={Pos:1504706560 Size:131072} in [{Pos:0 Size:1504953150}] - present true
2022/09/29 15:28:11 DEBUG : vfs cache: looking for range={Pos:1504837632 Size:115518} in [{Pos:0 Size:1504953150}] - present true
etexter@seraphim Downloads % grep present dropbox-mount.log | grep true | wc -l
    8623
etexter@seraphim Downloads % grep present dropbox-mount.log | grep false | wc -l
    2859
```

~80% came right from disk.

From Dropbox, I can see:

```
  1,410,105,344  48%   65.04MB/s    0:00:22
```

If I have a file already cached/downloaded, I use a SSD for my cache so it's fast.

```
  2,882,838,226 100%  539.60MB/s    0:00:05 (xfr#1, to-chk=0/1)
```

Something in the setup is creating slowness as the HDD is the point I'd check out.

**Comment by RemuxKid** [comment]
That's not possible. I removed the cache entirely before restarting the mount. In this test I removed the cache entirely with this updated config

```
[Unit]
Description=RClone Service Dropbox
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/home/mayur/.config/rclone/rclone.conf
RestartSec=5
ExecStart=/usr/bin/rclone mount db-secret: /mnt/Dropbox \
# This is for allowing users other than the user running rclone access to the mount
--allow-other \
--read-only \
# Dropbox is a polling remote so this value can be set very high and any changes are detected via polling.
--dir-cache-time 9999h \
# Log file location
--log-file /opt/rclone/logs/dropbox-mount.log \
# Set the log level
--log-level DEBUG \
# This is setting the file permission on the mount to user and group have the same access and other can read
--umask 002 \
# This sets up the remote control daemon so you can issue rc commands locally
--rc \
# This is the default port it runs on
--rc-addr 127.0.0.1:5580 \
# no-auth is used as no one else uses my server and it is not a shared seedbox
--rc-no-auth \
# The local disk used for caching
#--cache-dir=/cache/DB-TEST \
# This is used for caching files to local disk for streaming
#--vfs-cache-mode full \
# This limits the cache size to the value below
#--vfs-cache-max-size 800G \
# This limits the age in the cache if the size is reached and it removes the oldest files first
#--vfs-cache-max-age 9999h \
# Set the tpslimit
--tpslimit 12 \
# Set the tpslimit-burst
--tpslimit-burst 12 \
# Disable HTTP2
--disable-http2 
ExecStop=/bin/fusermount -uz /mnt/Dropbox
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:5580 _async=true
Restart=on-failure
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

Result (First pass)
```
rsync -P jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv ~/
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
1,504,953,150 100%   19.66MB/s    0:01:13 (xfr#1, to-chk=0/1)
```

Result (Second try)
```
rsync -P jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv ~/
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
1,504,953,150 100%   19.18MB/s    0:01:14 (xfr#1, to-chk=0/1)
```

With the original settings (with the cache removed with rm -rf

Result (First pass)
```
rsync -P jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv ~/
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
1,504,953,150 100%   23.23MB/s    0:01:01 (xfr#1, to-chk=0/1)
```

Result (Second try)
```
rsync -P jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv ~/
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
1,504,953,150 100%  398.89MB/s    0:00:03 (xfr#1, to-chk=0/1)
```

Second try with the cache on has a massive impact...

**Comment by animosity22** [comment]
I can only go by the logs as they show it was on disk with the present 'true'.

Other thing would be to test without the cache I'd imagine and you can see if the disk is the issue.

**Comment by RemuxKid** [comment]
I believe I've done this above, if I'm mistaken let me know.

But I'd say it's peering. This server is located in Germany, so I'd assume it's peering... But the copyto works perfectly fine... Odd.

**Comment by animosity22** [comment]
You can't compare a copy command vs a copy on a mount.

The first is multi threaded and the second is not.

```
2022/09/29 10:41:39 DEBUG : Creating backend with remote "/tmp/"
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: Need to transfer - File not found at Destination
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: Starting multi-thread copy with 4 parts of size 358.812Mi
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: multi-thread copy: stream 4/4 (1128726528-1504953150) size 358.798Mi starting
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: multi-thread copy: stream 2/4 (376242176-752484352) size 358.812Mi starting
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: multi-thread copy: stream 1/4 (0-376242176) size 358.812Mi starting
2022/09/29 10:41:39 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: multi-thread copy: stream 3/4 (752484352-1128726528) size 358.812Mi starting
```

I'd imagine both are equally as slow as you are masking the issue with multiple threads in the first.

**Comment by RemuxKid** [comment]
I've not compared the copy via command and a mount.

Those tests were both a mount. One with cache, other with it disabled.

The top result I posted was without a cache, and running the command twice to prove cache was off.

The bottom results show with a cache, where the second try eliminates the possibility of a slow drive.

**Comment by animosity22** [comment]
No - I am not.

I get this on a mount:

![image](https://user-images.githubusercontent.com/5088712/193065500-3050004f-9bc9-4cae-a202-efaa68eb2db7.png)

I get slightly more on a copy directly from dropbox since it multi threads.

**Comment by RemuxKid** [comment]
```
that's just peering.
```
I neglected this.

For the record, I wasn't comparing the copy command to the mount, I was comparing my mount speeds to your mount speeds. I'm aware of the differences of single vs multi-threads.

Thanks for the help :)
