### ISSUE TITLE
Removing Plex bloat

### ISSUE THREAD

**Issue by HushWorkDev** [animosity22/homescripts#99]
Hopefully this comes up as "Question" for you and not a "bug issue".

I was just reviewing your workflow, in ref to your configuration of Plex.. do you or have you got a method for removing some or all of the extra features bloat that Plex shows when you or ur users login and use it on web version?

**Comment by animosity22** [comment]
Not sure what you mean. Can you expand on what you mean?

**Comment by animosity22** [comment]
No idea - I'd suggest using the plex forums as that's pretty beyond anything here.
